// 报销单 · 杭州八月堪景 —— 每日花销随发随记
const reportInfo = {
  reportTitle: "报销单 · 杭州八月堪景",
  company: "廿一影视文化传播（上海）有限公司",
  submitter: "水素",
  project: "《竹林遗录》",
  department: "",
  period: "2026年8月（杭州堪景）",
  reportDate: "",
  loan: 100000,
};

const categoryOptions = [
  "交通费", "住宿费", "餐费", "汽车费用", "快递费", "办公用品", "器材", "业务招待费", "其他",
];

const expenseItems = [
  {
    id: 1,
    category: "交通费",
    description: "8/9 邱、赵、水三人高铁，北京-杭州",
    date: "2026-08-09",
    amount: 2004,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "中铁网络 12306",
  },
  {
    id: 2,
    category: "其他",
    description: "驱蚊水喷雾 3瓶（堪景户外用）",
    date: "2026-08-09",
    amount: 12.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "1688 绿壹(龙岩)生物技术 订单5127359942201006333，寄杭州桔子酒店前台",
  },
  {
    id: 3,
    category: "其他",
    description: "蕉下户外驱蚊器+3支驱蚊液（堪景户外用）",
    date: "2026-08-09",
    amount: 98.88,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "闲鱼 订单5126173704369015515（二手平台，无发票）",
  },
  {
    id: 4,
    category: "住宿费",
    description: "堪景期间酒店住宿（汇总）",
    date: "2026-08-10",
    amount: 1158.1,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-10_堪景酒店住宿两晚_付款截图_1158.10.png",
    invoiceFiles: ["invoices/extra/2026-08-10_堪景酒店住宿两晚_付款截图_1158.10.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "华住酒店集团，微信零钱通支付。8/10-8/12 两晚 2间房 3人：573.30 + 584.80 = 1158.10。后续堪景酒店费用继续累加到本条。发票到时候一起开",
  },
  {
    id: 5,
    category: "餐费",
    description: "8/10 水素高铁上午饭",
    date: "2026-08-10",
    amount: 30,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "发票已收到，待整理上传",
  },
  {
    id: 6,
    category: "交通费",
    description: "8/10 打车 到高铁站",
    date: "2026-08-10",
    amount: 33.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "打车费，以后整体一起开发票",
  },
];

const tpiaoList = [];
