// ============================================================
// 报销单 · 堪景贵州山东（5月）—— 已按飞书协同版更新
// 用途来自飞书「项目」列，住宿等已按几间/几晚合并，商户放在备注。
// 2026-08-01 已合入用户「导出全部改动」：挂载/抵票标记/顺序/合并/删除 全部固化。
// ============================================================

const reportInfo = {
  reportTitle: "报销单 · 堪景贵州山东（5月）",
  company: "廿一影视文化传播（上海）有限公司",
  submitter: "水素",
  project: "《竹林遗录》",
  department: "",
  period: "2026年5月（堪景 贵州+山东）",
  reportDate: "2026-07-07",
  loan: 5000,
};

const categoryOptions = [
  "交通费", "住宿费", "餐费", "汽车费用", "快递费", "办公用品", "器材", "业务招待费", "其他",
];

const expenseItems = [
  {
    id: 1,
    category: "交通费",
    description: "机票，北京-贵阳，kio",
    date: "2026-05-18",
    amount: 1520,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/up-001.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 1520,
    tpiaoIds: [],
    remark: "携程 单程机票北京贵阳",
  },
  {
    id: 2,
    category: "交通费",
    description: "机票，北京-贵阳，水素",
    date: "2026-05-18",
    amount: 760,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/up-002.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 760,
    tpiaoIds: [],
    remark: "携程 单程机票北京贵阳",
  },
  {
    id: 3,
    category: "交通费",
    description: "机票，南京-贵阳，lexie",
    date: "2026-05-18",
    amount: 670,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/up-003.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 670,
    tpiaoIds: [],
    remark: "携程 单程南京贵阳",
  },
  {
    id: 79,
    category: "交通费",
    description: "堪景打车前往机场",
    date: "2026-05-20",
    amount: 109,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-jichang-109.jpg",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 109,
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 4,
    category: "交通费",
    description: "贵阳 - 济南机票，kio水素lexie",
    date: "2026-05-24",
    amount: 2445,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-002.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 2445,
    tpiaoIds: [],
    remark: "Lexie 找馨yi 1104 转账备注:机票贵阳-济南 报销",
  },
  {
    id: 53,
    category: "交通费",
    description: "05/26 堪景打车",
    date: "2026-05-26",
    amount: 27.7,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-055.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 27.7,
    tpiaoIds: [],
    remark: "滴滴出行 滴滴快车打车-朱师傅-05月26日行程",
  },
  {
    id: 75513,
    category: "交通费",
    description: "5/27&5/28打车 1泰山-济南站，水素；泰山周老师晚饭打车返回；2泰山周老师晚饭打车往返",
    date: "2026-05-27",
    amount: 156.5,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-054.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 15.6,
    tpiaoIds: [],
    remark: "【合并】两程（燕师傅8.6 + 许师傅7.0）开在同一张票",
  },
  {
    id: 89,
    category: "交通费",
    description: "高铁，济南- 北京，水素",
    date: "2026-05-28",
    amount: 223,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/up-089.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 223,
    tpiaoIds: [],
    remark: "中铁网络 12306消费",
  },
  {
    id: 85,
    category: "交通费",
    description: "机票，济南-深圳，丘筠",
    date: "2026-05-30",
    amount: 1097,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-jipiao-1097a.jpg",
    invoiceFiles: ["invoices/kanjing/lx-jipiao-1097b.jpg"],
    invoiceCategory: "客运服务费",
    invoiceAmount: 1097,
    tpiaoIds: [],
    remark: "携程",
  },
  {
    id: 86,
    category: "交通费",
    description: "高铁，济南-北京，赵馨怡",
    date: "2026-05-30",
    amount: 223,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-gaotie-223.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 223,
    tpiaoIds: [],
    remark: "中铁网络 12306消费",
  },
  {
    id: 88,
    category: "交通费",
    description: "制片出行打车行程(见行程单)",
    date: "2026-05-31",
    amount: 363.68,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-didiA.pdf",
    invoiceFiles: ["invoices/kanjing/lx-didiB.pdf", "invoices/kanjing/lx-didiC.pdf", "invoices/kanjing/lx-didifpA.pdf", "invoices/kanjing/lx-didifpB.pdf", "invoices/kanjing/lx-didifpC.pdf"],
    invoiceCategory: "客运服务费",
    invoiceAmount: 363.68,
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 6,
    category: "住宿费",
    description: "5/20 - 5/22贵阳住宿，两间（kio，lexie，水素）",
    date: "2026-05-20",
    amount: 840,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-004.pdf",
    invoiceFiles: [],
    invoiceCategory: "住宿费",
    invoiceAmount: 840,
    tpiaoIds: [],
    remark: "贵州凯希尼酒店管理有限公司",
  },
  {
    id: 7,
    category: "住宿费",
    description: "5/23都匀住宿，三间（kio，lexie，水素，外联）",
    date: "2026-05-22",
    amount: 443,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/up-007.pdf",
    invoiceFiles: [],
    invoiceCategory: "住宿费",
    invoiceAmount: 443,
    tpiaoIds: [],
    remark: "携程旅行网 都匀港龙大酒店都匀石板古街店",
  },
  {
    id: 8,
    category: "住宿费",
    description: "5/24 贵阳住宿，两间（kio，lexie，水素）",
    date: "2026-05-24",
    amount: 266,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/up-008.pdf",
    invoiceFiles: [],
    invoiceCategory: "住宿费",
    invoiceAmount: 226,
    tpiaoIds: [],
    remark: "携程旅行网 凯亚德酒店贵阳龙洞堡机场砂之船奥特莱斯店",
  },
  {
    id: 10,
    category: "住宿费",
    description: "5/27 泰山住宿，两间（kio，lexie，水素）",
    date: "2026-05-24",
    amount: 660,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/up-010.pdf",
    invoiceFiles: [],
    invoiceCategory: "住宿费",
    invoiceAmount: 660,
    tpiaoIds: [],
    remark: "携程旅行网 白玉兰酒店（泰山景区岱庙店）",
  },
  {
    id: 9,
    category: "住宿费",
    description: "5/25-5/26 济南住宿，两间（kio，lexie，水素）",
    date: "2026-05-25",
    amount: 1054.6,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-006.pdf",
    invoiceFiles: ["invoices/kanjing/inv-007.pdf", "invoices/kanjing/inv-008.pdf", "invoices/kanjing/inv-009.pdf", "invoices/kanjing/inv-010.pdf", "invoices/kanjing/inv-011.pdf"],
    invoiceCategory: "住宿费",
    invoiceAmount: 255.8,
    tpiaoIds: [],
    remark: "华住酒店集团 桔子济南文化东路酒店,",
  },
  {
    id: 11,
    category: "住宿费",
    description: "5.28 济南住宿，两间（kio，lexie，水素）",
    date: "2026-05-28",
    amount: 525.3,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-037.pdf",
    invoiceFiles: ["invoices/kanjing/inv-038.pdf"],
    invoiceCategory: "住宿费",
    invoiceAmount: 1005.76,
    tpiaoIds: [],
    remark: "华住酒店集团 桔子济南文化东路酒店,",
  },
  {
    id: 12,
    category: "餐费",
    description: "5/20 晚饭，三人",
    date: "2026-05-20",
    amount: 73.5,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/dzfp_26524000000057008746_贵阳茶山上餐饮管理有限公司悦然时光分公司_20260722235613.pdf",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    invoiceAmount: 71.7,
    tpiaoIds: [],
    remark: "美团 去茶山（美的悦然时光店·咖啡·鲜奶茶·果茶）",
  },
  {
    id: 13,
    category: "餐费",
    description: "5/20 晚饭，三人",
    date: "2026-05-20",
    amount: 40.2,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0520 晚饭 3人 付款凭证.jpg",
    invoiceFiles: ["invoices/extra/抵票-廿一影视文化传播（上海）有限公司120.8.pdf"],
    invoiceCategory: "-",
    invoiceAmount: 0,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "美团 贞丰糯米饭（会展城店）",
  },
  {
    id: 67954,
    category: "餐费",
    description: "5/21 咖啡，3人",
    date: "2026-05-21",
    amount: 53.5,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/IMG_1543.JPG",
    invoiceFiles: ["invoices/extra/IMG_1542.JPG", "invoices/extra/IMG_1541.JPG"],
    invoiceCategory: "餐饮",
    invoiceAmount: 53.5,
    tpiaoIds: [],
    remark: "【合并】美团 Jillys Coffee茶几里（虎门巷店）；美团 Jillys Coffee茶几里（虎门巷店）；美团 Jillys Coffee茶几里（虎门巷店）",
  },
  {
    id: 17,
    category: "餐费",
    description: "5/21 早饭，四人",
    date: "2026-05-21",
    amount: 63,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0521 早饭 4人 付款凭证.PNG",
    invoiceFiles: ["invoices/extra/抵票-北京庆春朴门餐饮有限公司_发票金额227.00元.pdf"],
    invoiceCategory: "",
    invoiceAmount: 227,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "21/22/24共用21抵票；蒋家肠旺面",
  },
  {
    id: 18,
    category: "餐费",
    description: "5/21 午饭",
    date: "2026-05-21",
    amount: 93.5,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0521 午饭 4人 付款凭证.PNG",
    invoiceFiles: ["invoices/extra/抵票-北京庆春朴门餐饮有限公司_发票金额227.00元.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "21/22/24共用21抵票周菊珍 /",
  },
  {
    id: 19,
    category: "餐费",
    description: "5/21 晚饭",
    date: "2026-05-21",
    amount: 290,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/dzfp_26524000000051845731_花溪区孟关牛牛顺鲜牛馆_20260521182036.pdf",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: 290,
    tpiaoIds: [],
    remark: "孟关牛牛顺鲜牛馆 收款方备注:二维码收款付款方留言:0521晚饭",
  },
  {
    id: 94991,
    category: "餐费",
    description: "5/21 夜宵 - 三人；5/21 夜宵 - 三人",
    date: "2026-05-21",
    amount: 71.2,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0521 夜宵3人 2.jpg",
    invoiceFiles: ["invoices/extra/付款截图-0521 夜宵3人 1.jpg", "invoices/extra/抵票-北京庆春朴门餐饮有限公司_发票金额227.00元.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "21/22/24共用21抵票【合并】美团 喜三德甜品·糖水（冰浆·金融城店）；K 凯辉 10648大关3店",
  },
  {
    id: 65369,
    category: "餐费",
    description: "5/22 咖啡，三人",
    date: "2026-05-22",
    amount: 46.99,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/IMG_1546.JPG",
    invoiceFiles: ["invoices/extra/IMG_1545.JPG", "invoices/extra/IMG_1544.JPG"],
    invoiceCategory: "",
    invoiceAmount: 46.99,
    tpiaoIds: [],
    remark: "【合并】美团 25Gahwa（咖瓦咖啡面包）；美团 25Gahwa（咖瓦咖啡面包）；美团 25Gahwa（咖瓦咖啡面包）",
  },
  {
    id: 25,
    category: "餐费",
    description: "5/22 早饭，四人",
    date: "2026-05-22",
    amount: 52,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0522 早饭4人.jpg",
    invoiceFiles: ["invoices/extra/抵票-北京庆春朴门餐饮有限公司_发票金额471.00元.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "26/29/30 共用抵票；文荣粉面馆 贵阳观山湖文荣餐饮店",
  },
  {
    id: 26,
    category: "餐费",
    description: "5/22 水、纸巾等",
    date: "2026-05-22",
    amount: 67,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0522 午饭、水 .jpg",
    invoiceFiles: ["invoices/extra/抵票-北京酥麻引力餐饮管理有限公司_发票金额67.60元.pdf"],
    invoiceCategory: "餐饮",
    invoiceAmount: 67.6,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "清宇便利店-送货到家 收款方备注:二维码收款付款方留言:05/22 午饭便利店零食水",
  },
  {
    id: 27,
    category: "餐费",
    description: "5/22 晚饭，四人",
    date: "2026-05-22",
    amount: 39.3,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0522 晚饭3人.png",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: 39.3,
    tpiaoIds: [],
    remark: "美团 抹山序（甲秀楼店）",
  },
  {
    id: 28,
    category: "餐费",
    description: "5/22 晚饭，四人",
    date: "2026-05-22",
    amount: 305,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0522 晚饭 4人.jpg",
    invoiceFiles: ["invoices/extra/抵票-北京庆春朴门餐饮有限公司_发票金额471.00元.pdf"],
    invoiceCategory: "",
    invoiceAmount: 471,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "26/29/30 共用抵票；贵阳云岩刘丽军火锅店",
  },
  {
    id: 20108,
    category: "餐费",
    description: "0522 堪景路上用水、湿巾",
    date: "2026-05-22",
    amount: 28.6,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/dzfp_26522000000480381541_贵州黔邺超市有限公司_20260802013105.pdf",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: 28.6,
    tpiaoIds: [],
    remark: "堪景路上用水、湿巾",
  },
  {
    id: 29,
    category: "餐费",
    description: "5/23 路上面包",
    date: "2026-05-22",
    amount: 95.2,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0522 堪景行程干粮.PNG",
    invoiceFiles: ["invoices/extra/抵票-北京庆春朴门餐饮有限公司_发票金额471.00元.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "26/29/30 共用抵票；羊城西饼民生路店-消费",
  },
  {
    id: 30,
    category: "餐费",
    description: "5/23 路上零食",
    date: "2026-05-22",
    amount: 20,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/抵票-北京印象城徽巷里餐饮发展有限公司_发票金额23.90元 1.pdf",
    invoiceFiles: ["invoices/extra/付款截图-0522 堪景行程补给.PNG"],
    invoiceCategory: "餐饮费",
    invoiceAmount: 23.9,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "骆三姐土豆片店内购物",
  },
  {
    id: 32,
    category: "餐费",
    description: "5/23 咖啡，三人",
    date: "2026-05-23",
    amount: 72,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/dzfp_26524000000058058986_云岩区乔治咖啡文昌店_20260802013648-2-2.pdf",
    invoiceFiles: ["invoices/extra/58725ef1-578e-47a3-9e09-42ac68949b99756.pdf"],
    invoiceCategory: "餐饮费",
    invoiceAmount: 98.2,
    tpiaoIds: [],
    remark: "美团 CaptainGeorge乔治队长(文昌店)",
  },
  {
    id: 33,
    category: "餐费",
    description: "5/23 午饭",
    date: "2026-05-23",
    amount: 27,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0523 午饭 4人.PNG",
    invoiceFiles: ["invoices/extra/抵票-26112000002979155266-廿一影视文化传播（上海）有限公司.pdf"],
    invoiceCategory: "餐饮",
    invoiceAmount: 28.44,
    tpiaoIds: [],
    remark: "荭龄便利店 0523 午饭",
  },
  {
    id: 35,
    category: "餐费",
    description: "5/23 晚饭四人",
    date: "2026-05-23",
    amount: 238,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0523 晚饭 4人.PNG",
    invoiceFiles: ["invoices/extra/抵票-北京睿贝库餐饮服务有限公司_发票金额257.00元.pdf"],
    invoiceCategory: "餐饮费",
    invoiceAmount: 257,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "廖桂英 收款方备注:二维码收款付款方留言:0523 晚饭",
  },
  {
    id: 36,
    category: "餐费",
    description: "5/23 电影票 情书",
    date: "2026-05-23",
    amount: 91,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-阿嬷的情书电影票付款凭证.PNG",
    invoiceFiles: ["invoices/extra/抵票-廿一影视文化传播（上海）有限公司187.8.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "45/36共用45抵票；美团订单-26052311100300001306523700966830",
  },
  {
    id: 37,
    category: "餐费",
    description: "5/23 奶茶，三人",
    date: "2026-05-23",
    amount: 47,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/廿一影视文化传播（上海）有限公司发票26522000000788745286-2.pdf",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "CHAGEE霸王茶姬（贵州黔南都匀市星乐城店）",
  },
  {
    id: 102,
    category: "餐费",
    description: "0523 勘景早饭 四人",
    date: "2026-05-23",
    amount: 40,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0523 早饭4人.JPG",
    invoiceFiles: ["invoices/extra/抵票-dzfp_26114000000037123126_北京天恒常湘餐饮有限公司_20260519151818.pdf"],
    invoiceCategory: "",
    invoiceAmount: 229,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 103,
    category: "餐费",
    description: "0523 勘景午饭 四人",
    date: "2026-05-23",
    amount: 121,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0523 午饭 4人.JPG",
    invoiceFiles: ["invoices/extra/抵票-dzfp_26114000000037123126_北京天恒常湘餐饮有限公司_20260519151818.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 111474,
    category: "餐费",
    description: "5/24 堪景咖啡，三人",
    date: "2026-05-24",
    amount: 38.4,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0524 堪景咖啡3人2 .PNG",
    invoiceFiles: ["invoices/extra/付款截图-0524 堪景咖啡3人.PNG", "invoices/extra/抵票-dzfp_26114000000037123126_北京天恒常湘餐饮有限公司_20260519151818.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "【合并】美团 库迪咖啡(都匀万达广场店)；美团 库迪咖啡(都匀万达广场店)",
  },
  {
    id: 41,
    category: "餐费",
    description: "05/24 堪景早饭，4人",
    date: "2026-05-24",
    amount: 39,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/抵票-26117000000636225049 1.pdf",
    invoiceFiles: ["invoices/extra/付款截图-0524 早饭4人.PNG"],
    invoiceCategory: "餐饮费",
    invoiceAmount: 40,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "老苹果 收款方备注:二维码收款付款方留言:0524早飯",
  },
  {
    id: 42712,
    category: "餐费",
    description: "05/24 晚饭，四人；05/24 晚饭，四人",
    date: "2026-05-24",
    amount: 369.7,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0524 晚饭3人.jpeg",
    invoiceFiles: ["invoices/kanjing/inv-003.pdf"],
    invoiceCategory: "餐饮",
    invoiceAmount: 295,
    tpiaoIds: [],
    remark: "晚饭+奶茶",
  },
  {
    id: 44,
    category: "餐费",
    description: "05/24 夜宵，三人",
    date: "2026-05-24",
    amount: 42.5,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0524 夜宵 3人.pdf",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "美团 ZOONANA首尔炸鸡（太升国际店）",
  },
  {
    id: 45,
    category: "餐费",
    description: "05/24 夜宵，三人",
    date: "2026-05-24",
    amount: 43.7,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0524 夜宵 3人 3.pdf",
    invoiceFiles: ["invoices/extra/0524 夜宵 3人 2.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "美团 首杨水果（首钢二店）",
  },
  {
    id: 46,
    category: "餐费",
    description: "05/25 咖啡，三人",
    date: "2026-05-25",
    amount: 95.6,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0525 咖啡3人.PNG",
    invoiceFiles: ["invoices/extra/抵票-廿一影视文化传播（上海）有限公司187.8.pdf"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "45/36共用45抵票；去茶山 【堂食】_贵阳机场店T3航站楼（安检内）_267945",
  },
  {
    id: 34247,
    category: "餐费",
    description: "05/26 爬山补给、干粮、装备，6人",
    date: "2026-05-25",
    amount: 520.52,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0526 爬山补给 6 人.pdf",
    invoiceFiles: ["invoices/kanjing/inv-036.pdf", "invoices/kanjing/inv-022.pdf", "invoices/kanjing/inv-041.pdf"],
    invoiceCategory: "餐饮",
    invoiceAmount: 520.52,
    tpiaoIds: [],
    remark: "【合并】美团 711便利店（诚基中心店）；美团 名创优品24小时超级店（济南诚基中心店）；美团 松鼠便利（山师店）；美团 松鼠便利（窑头店）",
  },
  {
    id: 51,
    category: "餐费",
    description: "05/26 咖啡，三人",
    date: "2026-05-26",
    amount: 35.9,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0526 咖啡 3人.pdf",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: 35.9,
    tpiaoIds: [],
    remark: "luckin coffee 订单付款",
  },
  {
    id: 52,
    category: "餐费",
    description: "05/26 早饭，六人",
    date: "2026-05-26",
    amount: 57,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0526 早饭付款凭证.png",
    invoiceFiles: ["invoices/extra/抵票-廿一影视文化传播（上海）有限公司120.8.pdf"],
    invoiceCategory: "",
    invoiceAmount: 120,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "48/19共用48 抵票；晋同源快餐店",
  },
  {
    id: 54,
    category: "餐费",
    description: "05/26 姜汤，三人",
    date: "2026-05-26",
    amount: 31.6,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/dzfp_26372000002509379221_济南市章丘区燕归来燕窝馆（个体工商户）_20260801181809.pdf",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: 31.6,
    tpiaoIds: [],
    remark: "美团 暖燕·姨妈热饮·现炖燕窝(山师店)",
  },
  {
    id: 73603,
    category: "餐费",
    description: "05/26 晚饭，三人；05/26 晚饭，三人",
    date: "2026-05-26",
    amount: 265.11,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0526 晚饭发票.png",
    invoiceFiles: ["invoices/extra/IMG_1550.PNG"],
    invoiceCategory: "餐饮",
    invoiceAmount: 265.11,
    tpiaoIds: [],
    remark: "【合并】美团 【元神御金汤】百合虫草花炖鲜鸡汤等10件商品；美团 【Street Shark（山师店）】美式经典芝士牛堡  …",
  },
  {
    id: 80335,
    category: "餐费",
    description: "05/26 爬山装备，六人",
    date: "2026-05-26",
    amount: 79.4,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0526 爬山装备 1.pdf",
    invoiceFiles: ["invoices/extra/0526 爬山装备 2.pdf", "invoices/extra/0526 爬山装备4.pdf", "invoices/extra/0526 爬山装备 3.pdf"],
    invoiceCategory: "",
    invoiceAmount: 79.4,
    tpiaoIds: [],
    remark: "【合并】美团 松鼠便利（窑头店）；美团 松鼠便利（窑头店）",
  },
  {
    id: 61,
    category: "餐费",
    description: "05/26 爬山干粮，六人",
    date: "2026-05-26",
    amount: 76.58,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0527 爬山干粮.PNG",
    invoiceFiles: ["invoices/extra/抵票-北京象鲜科技有限公司_发票金额77.47元.pdf"],
    invoiceCategory: "",
    invoiceAmount: 77.47,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "美团 711便利店（济南山师大北门店）",
  },
  {
    id: 62,
    category: "餐费",
    description: "05/27 咖啡，三人",
    date: "2026-05-27",
    amount: 52.8,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0527 咖啡3人.pdf",
    invoiceFiles: ["invoices/extra/0527 咖啡3人 2.pdf"],
    invoiceCategory: "餐饮",
    invoiceAmount: 52.8,
    tpiaoIds: [],
    remark: "美团 WE LUCKY COFFEE现磨咖啡果茶（山大北路店）",
  },
  {
    id: 63,
    category: "餐费",
    description: "05/27 灵岩寺午饭，6人",
    date: "2026-05-27",
    amount: 134,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0527午饭补给.PNG",
    invoiceFiles: ["invoices/extra/抵票-dzfp_26112000002815373431_廿一影视文化传播（上海）有限公司_20260802025515.pdf"],
    invoiceCategory: "餐饮",
    invoiceAmount: 173,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "山东丝路灵岩文化旅游有限公司运",
  },
  {
    id: 67,
    category: "餐费",
    description: "5/27 三人奶茶",
    date: "2026-05-27",
    amount: 70,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/7bd62477-151e-4954-88a6-01b407d7699d756.pdf",
    invoiceFiles: ["invoices/extra/84ff0f1a-7b30-492e-8571-ae62d216952f596.pdf"],
    invoiceCategory: "餐饮",
    invoiceAmount: 70,
    tpiaoIds: [],
    remark: "美团 喜茶(泰安金桥城店)",
  },
  {
    id: 68,
    category: "餐费",
    description: "5/28 泰山干粮，六人",
    date: "2026-05-27",
    amount: 58.52,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-021.pdf",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    invoiceAmount: 58.52,
    tpiaoIds: [],
    remark: "美团 松鼠便利（泰安万达店）",
  },
  {
    id: 69,
    category: "餐费",
    description: "5/28 泰山干粮，六人",
    date: "2026-05-27",
    amount: 34.47,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-5_28_泰山干粮，六人-2.png",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "美团 好想来品牌零食（泰安泰山区东湖公园店）",
  },
  {
    id: 70,
    category: "餐费",
    description: "5/28 咖啡，三人",
    date: "2026-05-28",
    amount: 67.9,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-024.pdf",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    invoiceAmount: 67.9,
    tpiaoIds: [],
    remark: "美团 肯悦咖啡（泰安银座店）",
  },
  {
    id: 92193,
    category: "餐费",
    description: "5/28 泰山午饭，六人；5/28 泰山午饭，六人；5/28 泰山午饭，六人",
    date: "2026-05-28",
    amount: 293,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0528 泰山 午饭 6人 3.PNG",
    invoiceFiles: ["invoices/extra/付款截图-0528 泰山 午饭 6人 2.PNG", "invoices/extra/付款截图-0528 泰山 午饭 6人 1.PNG", "invoices/extra/抵票-北京昀庭餐饮文化管理有限公司_发票金额485.00元.pdf"],
    invoiceCategory: "餐饮服务",
    invoiceAmount: 485,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "53/59共用59抵票【合并】泰安市可栗香；沪上阿姨 【堂食】_泰安泰山景区店_61318_37090204247；昌盛快餐 /",
  },
  {
    id: 80,
    category: "餐费",
    description: "5/20 堪景打车前往机场",
    date: "2026-05-28",
    amount: 131.6,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-dinner-131.jpg",
    invoiceFiles: ["invoices/kanjing/up-080.pdf"],
    invoiceCategory: "餐饮",
    invoiceAmount: 131.6,
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 81,
    category: "餐费",
    description: "导演、制片出发咖啡",
    date: "2026-05-29",
    amount: 35.72,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-coffee-35.jpg",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    invoiceAmount: 35.72,
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 82,
    category: "餐费",
    description: "导演、制片、协拍4人早餐",
    date: "2026-05-29",
    amount: 92,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-breakfast-92.jpg",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    invoiceAmount: 92,
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 118542,
    category: "餐费",
    description: "5/28 泰山上水；5/28 泰山上水；5/28 泰山上水；5/28 泰山上水",
    date: "2026-05-28",
    amount: 180,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0528 泰山上买水4.PNG",
    invoiceFiles: ["invoices/extra/付款截图-0528 泰山上买水3.PNG", "invoices/extra/付款截图-0528 泰山上买水2.PNG", "invoices/extra/付款截图-0528 泰山上买水1.PNG", "invoices/extra/抵票-北京昀庭餐饮文化管理有限公司_发票金额485.00元.pdf"],
    invoiceCategory: "",
    invoiceAmount: 0,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "53/59共用59抵票；【合并】无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...；无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...；无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...；无人售货机 盛马售货机仅售2999元-外星人电解质水外星人电解质水外星人...",
  },
  {
    id: 58,
    category: "餐费",
    description: "05/26 爬山干粮补给",
    date: "2026-05-26",
    amount: 213.52,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/Weixin Image_20260731174118_458_7.png",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 109676,
    category: "汽车费用",
    description: "堪景停车费",
    date: "2026-05-20",
    amount: 30,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-0523 停车费.png",
    invoiceFiles: ["invoices/extra/付款截图-0523停车费.png", "invoices/extra/付款截图-0522停车费.png", "invoices/extra/付款截图-0520停车费2.png", "invoices/extra/付款截图-0520停车费.png", "invoices/extra/抵票-26112000002979155266-廿一影视文化传播（上海）有限公司-2.pdf"],
    invoiceCategory: "餐饮费",
    invoiceAmount: 32.6,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "【合并】杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）；杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）；杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）；杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）；杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 91,
    category: "汽车费用",
    description: "堪景油费",
    date: "2026-05-22",
    amount: 520,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-youfei-520.pdf",
    invoiceFiles: [],
    invoiceCategory: "成品油",
    invoiceAmount: 520,
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 76052,
    category: "汽车费用",
    description: "勘景过路费；勘景过路费；勘景过路费；勘景过路费",
    date: "2026-05-22",
    amount: 128.21,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-gonglu-2.pdf",
    invoiceFiles: ["invoices/kanjing/tq-gonglu-3.pdf", "invoices/kanjing/tq-gonglu-4.pdf", "invoices/kanjing/tq-gonglu-1.pdf", "invoices/extra/trans.pdf"],
    invoiceCategory: "通行费",
    invoiceAmount: 128.21,
    tpiaoIds: [],
    remark: "【合并】杨天奇 贵阳/都匀勘景实报（合计3465.07）；杨天奇 贵阳/都匀勘景实报（合计3465.07）；杨天奇 贵阳/都匀勘景实报（合计3465.07）；杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 92,
    category: "汽车费用",
    description: "勘景油费",
    date: "2026-05-25",
    amount: 625.86,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-youfei-625.pdf",
    invoiceFiles: [],
    invoiceCategory: "成品油",
    invoiceAmount: 625.86,
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 65,
    category: "快递费",
    description: "5/27 闪送费用",
    date: "2026-05-27",
    amount: 45.28,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/抵票-7498fb6be95ebed3435e8b68f38be3eb.jpg",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    invoiceAmount: 45.9,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "滴滴出行 订单费用",
  },
  {
    id: 34,
    category: "快递费",
    description: "5/23 快递费",
    date: "2026-05-23",
    amount: 41,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/dzfp_26527000000087512492_20260801172519.pdf",
    invoiceFiles: [],
    invoiceCategory: "收派服务",
    invoiceAmount: 41,
    tpiaoIds: [],
    remark: "德邦快递-DPK202747902521",
  },
  {
    id: 83,
    category: "快递费",
    description: "器材快递回租赁公司(济南→北京)",
    date: "2026-05-29",
    amount: 106,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-sf-106.pdf",
    invoiceFiles: [],
    invoiceCategory: "收派服务",
    invoiceAmount: 106,
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 84,
    category: "快递费",
    description: "器材电池闪送回租赁公司",
    date: "2026-05-30",
    amount: 80,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-shansong-80.pdf",
    invoiceFiles: [],
    invoiceCategory: "快递服务",
    invoiceAmount: 80,
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 5,
    category: "器材",
    description: "堪景胶片",
    date: "2026-05-19",
    amount: 1710,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-胶片购买凭证.PNG",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "朱媛 收款方备注:二维码收款付款方留言:portra 160 /45一盒+ HP5/45 两盒",
  },
  {
    id: 104,
    category: "器材",
    description: "无人机租赁(400元/天×5)",
    date: "2026-05-31",
    amount: 2000,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "外联支付",
  },
  {
    id: 106,
    category: "器材",
    description: "器材租赁",
    date: "2026-06-02",
    amount: 2000,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-堪景器材租赁凭证.PNG",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "枪枪影视-器材租赁部 枪枪影视-器材租赁部 转账备注:5月20–29日10天器材租赁费用",
  },
  {
    id: 78,
    category: "业务招待费",
    description: "给堪景外联制片买烟",
    date: "2026-05-18",
    amount: 530,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-给堪景外联制片买烟_买烟(外联)_530.00.jpg",
    invoiceFiles: ["invoices/extra/抵票-廿一影视文化传播（上海）有限公司70.pdf", "invoices/extra/抵票-dzfp_26522000000664429156_都匀市干平便利店_20260702180237.pdf"],
    invoiceCategory: "餐饮费",
    invoiceAmount: 220,
    tpiaoIds: [],
    dipiaoFlag: true,
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 55,
    category: "其他",
    description: "05/26 药",
    date: "2026-05-26",
    amount: 27,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/0526 药配送费 发票.pdf",
    invoiceFiles: ["invoices/extra/0526 药 发票.pdf"],
    invoiceCategory: "",
    invoiceAmount: 27,
    tpiaoIds: [],
    remark: "美团 北京同仁堂（历山店）",
  },
  {
    id: 64,
    category: "其他",
    description: "05/27 爬山护具",
    date: "2026-05-27",
    amount: 269.02,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/爬山护具发票.jpg",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: 269.02,
    tpiaoIds: [],
    remark: "京东-订单编号3511486014052261",
  },
  {
    id: 105,
    category: "其他",
    description: "贵州外联费用",
    date: "2026-05-31",
    amount: 5000,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/付款截图-贵州堪景外联红包.PNG",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "杨天奇 转账备注:堪景红包🧧",
  },
];

const tpiaoList = [];
