// ============================================================
// 报销单数据文件 —— 由微信流水（堪景出差 2026-05~06）自动生成
// 发票状态暂时都标为 none（无凭证），等 Google Drive 发票对应后再逐笔更新。
// ============================================================

const reportInfo = {
  reportTitle: "报销单",
  submitter: "水素",
  department: "",
  period: "2026年5-6月（堪景出差）",
  reportDate: "2026-07-03",
};

const categoryOptions = [
  "交通费",
  "差旅-交通",
  "住宿费",
  "餐费",
  "汽车费用",
  "快递费",
  "办公用品",
  "业务招待费",
  "其他",
];

const expenseItems = [
  {
    id: 1,
    category: "差旅-交通",
    description: "携程 单程机票北京贵阳",
    date: "2026-05-18",
    amount: 1520.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 2,
    category: "差旅-交通",
    description: "携程 单程机票北京贵阳",
    date: "2026-05-18",
    amount: 760.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 3,
    category: "差旅-交通",
    description: "携程 单程南京贵阳",
    date: "2026-05-18",
    amount: 670.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 4,
    category: "其他",
    description: "朱媛 收款方备注:二维码收款付款方留言:portra 160 /45一盒+ HP5/4",
    date: "2026-05-19",
    amount: 1710.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 5,
    category: "住宿费",
    description: "贵州凯希尼酒店管理有限公司",
    date: "2026-05-20",
    amount: 280.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 6,
    category: "餐费",
    description: "美团 去茶山（美的悦然时光店·咖啡·鲜奶茶·果茶）",
    date: "2026-05-20",
    amount: 73.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 7,
    category: "餐费",
    description: "美团 贞丰糯米饭（会展城店）",
    date: "2026-05-20",
    amount: 40.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 8,
    category: "餐费",
    description: "美团 Jillys Coffee茶几里（虎门巷店）",
    date: "2026-05-21",
    amount: 15.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 9,
    category: "餐费",
    description: "美团 Jillys Coffee茶几里（虎门巷店）",
    date: "2026-05-21",
    amount: 15.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 10,
    category: "餐费",
    description: "美团 Jillys Coffee茶几里（虎门巷店）",
    date: "2026-05-21",
    amount: 23.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 11,
    category: "餐费",
    description: "蒋家肠旺面",
    date: "2026-05-21",
    amount: 63.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 12,
    category: "其他",
    description: "周菊珍 /",
    date: "2026-05-21",
    amount: 93.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 13,
    category: "餐费",
    description: "孟关牛牛顺鲜牛馆 收款方备注:二维码收款付款方留言:0521晚饭",
    date: "2026-05-21",
    amount: 290.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 14,
    category: "餐费",
    description: "美团 喜三德甜品·糖水（冰浆·金融城店）",
    date: "2026-05-21",
    amount: 26.68,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 15,
    category: "餐费",
    description: "K 凯辉 10648大关3店",
    date: "2026-05-21",
    amount: 44.52,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 16,
    category: "住宿费",
    description: "贵州凯希尼酒店管理有限公司",
    date: "2026-05-21",
    amount: 280.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 17,
    category: "住宿费",
    description: "贵州凯希尼酒店管理有限公司",
    date: "2026-05-22",
    amount: 280.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 18,
    category: "餐费",
    description: "美团 25Gahwa（咖瓦咖啡面包）",
    date: "2026-05-22",
    amount: 16.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 19,
    category: "餐费",
    description: "美团 25Gahwa（咖瓦咖啡面包）",
    date: "2026-05-22",
    amount: 20.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 20,
    category: "餐费",
    description: "美团 25Gahwa（咖瓦咖啡面包）",
    date: "2026-05-22",
    amount: 18.59,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 21,
    category: "餐费",
    description: "文荣粉面馆 贵阳观山湖文荣餐饮店",
    date: "2026-05-22",
    amount: 52.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 22,
    category: "餐费",
    description: "清宇便利店-送货到家 收款方备注:二维码收款付款方留言:05/22 午饭便利店零食水",
    date: "2026-05-22",
    amount: 67.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 23,
    category: "餐费",
    description: "美团 抹山序（甲秀楼店）",
    date: "2026-05-22",
    amount: 39.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 24,
    category: "餐费",
    description: "贵阳云岩刘丽军火锅店",
    date: "2026-05-22",
    amount: 305.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 25,
    category: "餐费",
    description: "羊城西饼民生路店-消费",
    date: "2026-05-22",
    amount: 95.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 26,
    category: "餐费",
    description: "骆三姐土豆片店内购物",
    date: "2026-05-22",
    amount: 20.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 27,
    category: "其他",
    description: "辣辣辣里辣 转账备注:濕巾水",
    date: "2026-05-22",
    amount: 28.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 28,
    category: "差旅-交通",
    description: "携程旅行网 都匀港龙大酒店都匀石板古街店",
    date: "2026-05-22",
    amount: 84.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 29,
    category: "差旅-交通",
    description: "携程旅行网 都匀港龙大酒店都匀石板古街店",
    date: "2026-05-22",
    amount: 187.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 30,
    category: "差旅-交通",
    description: "携程旅行网 都匀港龙大酒店都匀石板古街店",
    date: "2026-05-22",
    amount: 172.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 31,
    category: "餐费",
    description: "美团 CaptainGeorge乔治队长(文昌店)",
    date: "2026-05-23",
    amount: 72.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 32,
    category: "餐费",
    description: "荭龄便利店 0523 午饭",
    date: "2026-05-23",
    amount: 27.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 33,
    category: "快递费",
    description: "德邦快递-DPK202747902521",
    date: "2026-05-23",
    amount: 41.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 34,
    category: "餐费",
    description: "廖桂英 收款方备注:二维码收款付款方留言:0523 晚饭",
    date: "2026-05-23",
    amount: 238.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 35,
    category: "餐费",
    description: "美团订单-26052311100300001306523700966830",
    date: "2026-05-23",
    amount: 91.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 36,
    category: "餐费",
    description: "CHAGEE霸王茶姬（贵州黔南都匀市星乐城店）",
    date: "2026-05-23",
    amount: 47.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 37,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-贾师傅-05月20日行程",
    date: "2026-05-23",
    amount: 127.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 38,
    category: "餐费",
    description: "美团 库迪咖啡(都匀万达广场店)",
    date: "2026-05-24",
    amount: 22.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 39,
    category: "餐费",
    description: "美团 库迪咖啡(都匀万达广场店)",
    date: "2026-05-24",
    amount: 15.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 40,
    category: "交通费",
    description: "滴滴出行 滴滴打车-尹师傅",
    date: "2026-05-24",
    amount: 8.01,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 41,
    category: "餐费",
    description: "老苹果 收款方备注:二维码收款付款方留言:0524早飯",
    date: "2026-05-24",
    amount: 39.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 42,
    category: "差旅-交通",
    description: "携程旅行网 凯亚德酒店贵阳龙洞堡机场砂之船奥特莱斯店",
    date: "2026-05-24",
    amount: 138.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 43,
    category: "差旅-交通",
    description: "携程旅行网 凯亚德酒店贵阳龙洞堡机场砂之船奥特莱斯店",
    date: "2026-05-24",
    amount: 128.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 44,
    category: "餐费",
    description: "美团 去茶山（国贸新印1950店·咖啡·鲜奶茶·果茶）",
    date: "2026-05-24",
    amount: 74.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 45,
    category: "餐费",
    description: "听涛拍岸 转账备注:0524 晚飯",
    date: "2026-05-24",
    amount: 295.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 46,
    category: "差旅-交通",
    description: "Lexie 找馨yi 1104 转账备注:机票贵阳-济南 报销",
    date: "2026-05-24",
    amount: 2445.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 47,
    category: "餐费",
    description: "美团 ZOONANA首尔炸鸡（太升国际店）",
    date: "2026-05-24",
    amount: 43.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 48,
    category: "餐费",
    description: "美团 首杨水果（首钢二店）",
    date: "2026-05-24",
    amount: 43.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 49,
    category: "餐费",
    description: "去茶山 【堂食】_贵阳机场店T3航站楼（安检内）_267945",
    date: "2026-05-25",
    amount: 95.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 50,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,订单编号:250013626052511473533000",
    date: "2026-05-25",
    amount: 242.65,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 51,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,订单编号:250013626052511534803900",
    date: "2026-05-25",
    amount: 271.15,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 52,
    category: "餐费",
    description: "美团 711便利店（诚基中心店）",
    date: "2026-05-25",
    amount: 340.83,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 53,
    category: "餐费",
    description: "美团 名创优品24小时超级店（济南诚基中心店）",
    date: "2026-05-25",
    amount: 65.82,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 54,
    category: "餐费",
    description: "美团 松鼠便利（山师店）",
    date: "2026-05-25",
    amount: 74.94,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 55,
    category: "餐费",
    description: "美团 松鼠便利（窑头店）",
    date: "2026-05-25",
    amount: 59.93,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 56,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,订单编号:250013626052601481469600",
    date: "2026-05-26",
    amount: 261.15,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 57,
    category: "餐费",
    description: "luckin coffee 订单付款",
    date: "2026-05-26",
    amount: 35.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 58,
    category: "餐费",
    description: "晋同源兰悦中心店订单",
    date: "2026-05-26",
    amount: 57.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 59,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,订单编号:250013626052609492771100",
    date: "2026-05-26",
    amount: 279.65,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 60,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-朱师傅-05月26日行程",
    date: "2026-05-26",
    amount: 27.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 61,
    category: "餐费",
    description: "美团 暖燕·姨妈热饮·现炖燕窝(山师店)",
    date: "2026-05-26",
    amount: 31.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 62,
    category: "餐费",
    description: "美团 北京同仁堂（历山店）",
    date: "2026-05-26",
    amount: 27.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 63,
    category: "餐费",
    description: "美团 【元神御金汤】百合虫草花炖鲜鸡汤等10件商品",
    date: "2026-05-26",
    amount: 121.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 64,
    category: "餐费",
    description: "美团 【Street Shark（山师店）】美式经典芝士牛堡  …",
    date: "2026-05-26",
    amount: 144.01,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 65,
    category: "其他",
    description: "辣辣辣里辣 转账备注:微信转账",
    date: "2026-05-26",
    amount: 213.52,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 66,
    category: "餐费",
    description: "美团 松鼠便利（窑头店）",
    date: "2026-05-26",
    amount: 41.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 67,
    category: "餐费",
    description: "美团 松鼠便利（窑头店）",
    date: "2026-05-26",
    amount: 38.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 68,
    category: "餐费",
    description: "美团 711便利店（济南山师大北门店）",
    date: "2026-05-26",
    amount: 76.58,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 69,
    category: "其他",
    description: "辣辣辣里辣 转账备注:微信转账",
    date: "2026-05-27",
    amount: 375.88,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 70,
    category: "住宿费",
    description: "辣辣辣里辣 转账备注:酒店",
    date: "2026-05-27",
    amount: 359.88,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 71,
    category: "餐费",
    description: "美团 WE LUCKY COFFEE现磨咖啡果茶（山大北路店）",
    date: "2026-05-27",
    amount: 52.59,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 72,
    category: "其他",
    description: "山东丝路灵岩文化旅游有限公司运",
    date: "2026-05-27",
    amount: 134.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 73,
    category: "其他",
    description: "京东-订单编号3511486014052261",
    date: "2026-05-27",
    amount: 269.02,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 74,
    category: "交通费",
    description: "滴滴出行 订单费用",
    date: "2026-05-27",
    amount: 45.28,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 75,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-燕师傅-05月27日行程",
    date: "2026-05-27",
    amount: 8.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 76,
    category: "餐费",
    description: "美团 喜茶(泰安金桥城店)",
    date: "2026-05-27",
    amount: 70.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 77,
    category: "餐费",
    description: "美团 松鼠便利（泰安万达店）",
    date: "2026-05-27",
    amount: 58.52,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 78,
    category: "餐费",
    description: "美团 好想来品牌零食（泰安泰山区东湖公园店）",
    date: "2026-05-27",
    amount: 34.47,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 79,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-许师傅-05月27日行程",
    date: "2026-05-28",
    amount: 7.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 80,
    category: "餐费",
    description: "美团 肯悦咖啡（泰安银座店）",
    date: "2026-05-28",
    amount: 67.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 81,
    category: "餐费",
    description: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 82,
    category: "餐费",
    description: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
    date: "2026-05-28",
    amount: 36.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 83,
    category: "餐费",
    description: "无人售货机 盛马售货机仅售2999元-外星人电解质水外星人电解质水外星人...",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 84,
    category: "餐费",
    description: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 85,
    category: "餐费",
    description: "泰安市可栗香",
    date: "2026-05-28",
    amount: 40.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 86,
    category: "餐费",
    description: "沪上阿姨 【堂食】_泰安泰山景区店_61318_37090204247",
    date: "2026-05-28",
    amount: 57.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 87,
    category: "餐费",
    description: "昌盛快餐 /",
    date: "2026-05-28",
    amount: 196.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 88,
    category: "其他",
    description: "Lexie 找馨yi 1104 转账备注:堪景备用金",
    date: "2026-05-28",
    amount: 5000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 89,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,订单编号:250013626052821154807700",
    date: "2026-05-28",
    amount: 525.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 90,
    category: "差旅-交通",
    description: "中铁网络 12306消费",
    date: "2026-05-28",
    amount: 223.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 91,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-刘师傅-05月28日行程",
    date: "2026-05-28",
    amount: 174.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 92,
    category: "其他",
    description: "转账备注:贵州都匀堪景报销-杨天奇",
    date: "2026-05-31",
    amount: 3465.07,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 93,
    category: "其他",
    description: "杨天奇 转账备注:堪景红包🧧",
    date: "2026-05-31",
    amount: 5000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 94,
    category: "办公用品",
    description: "枪枪影视-器材租赁部 枪枪影视-器材租赁部 转账备注:5月20–29日10天器材租赁费用",
    date: "2026-06-02",
    amount: 2000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 95,
    category: "住宿费",
    description: "华住酒店集团 全季上海延安路酒店,订单编号:2000521260604164403930006",
    date: "2026-06-04",
    amount: 3887.09,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 96,
    category: "差旅-交通",
    description: "携程 单程深圳上海，kio",
    date: "2026-06-05",
    amount: 680.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 97,
    category: "差旅-交通",
    description: "中铁网络 12306消费",
    date: "2026-06-05",
    amount: 661.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 98,
    category: "餐费",
    description: "美团平台商户 南洋記Asian Fusion BistroEatery-大众点评App-260",
    date: "2026-06-09",
    amount: 83.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 99,
    category: "餐费",
    description: "美团平台商户 南洋記Asian Fusion BistroEatery-大众点评App-260",
    date: "2026-06-09",
    amount: 87.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 100,
    category: "餐费",
    description: "美团平台商户 南洋記Asian Fusion BistroEatery-大众点评App-260",
    date: "2026-06-09",
    amount: 87.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 101,
    category: "餐费",
    description: "南洋记现代东南亚餐酒馆扫码收款",
    date: "2026-06-09",
    amount: 170.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 102,
    category: "餐费",
    description: "间枚playlet 网上购物202606100411177729",
    date: "2026-06-10",
    amount: 105.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 103,
    category: "餐费",
    description: "黃啓雲私房牛肉面工坊（金地新华道店） 美团/大众点评点餐订单-0610502605549676691",
    date: "2026-06-10",
    amount: 114.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 104,
    category: "餐费",
    description: "蓝瓶咖啡",
    date: "2026-06-10",
    amount: 112.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 105,
    category: "餐费",
    description: "团子（番禺路店） 团子tuanzi·bread·cafe订单",
    date: "2026-06-10",
    amount: 16.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 106,
    category: "餐费",
    description: "另茶 【堂食】_上海幸福里店_44548_3010004",
    date: "2026-06-10",
    amount: 23.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 107,
    category: "餐费",
    description: "美团 Bonzest云南板札咖啡（中山公园店）",
    date: "2026-06-11",
    amount: 21.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 108,
    category: "餐费",
    description: "美团 Bonzest云南板札咖啡（中山公园店）",
    date: "2026-06-11",
    amount: 21.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 109,
    category: "餐费",
    description: "intree 木里  韩式创意菜 美团/大众点评点餐订单-061150260555388426486",
    date: "2026-06-11",
    amount: 141.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 110,
    category: "餐费",
    description: "lemonlouis咖啡店 购买商品",
    date: "2026-06-11",
    amount: 23.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 111,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-闫师傅-06月11日行程",
    date: "2026-06-11",
    amount: 11.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 112,
    category: "餐费",
    description: "不许养鱼Bistro 上海首店 美团收银909700213588445969",
    date: "2026-06-12",
    amount: 391.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 113,
    category: "餐费",
    description: "美团 喜茶(上海汇京国际店)",
    date: "2026-06-12",
    amount: 63.4,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 114,
    category: "餐费",
    description: "超级·牛肉粉 美团/大众点评点餐订单-06124881940417942486705",
    date: "2026-06-12",
    amount: 150.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 115,
    category: "餐费",
    description: "美团 小山堂(港汇恒隆广场店)",
    date: "2026-06-12",
    amount: 45.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 116,
    category: "餐费",
    description: "美团 Bonzest云南板札咖啡（中山公园店）",
    date: "2026-06-12",
    amount: 26.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 117,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-臧师傅-06月11日行程",
    date: "2026-06-12",
    amount: 60.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 118,
    category: "餐费",
    description: "美团 去茶山（上海环贸店·咖啡·鲜奶茶·果茶）",
    date: "2026-06-13",
    amount: 59.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 119,
    category: "餐费",
    description: "美团 世纪精品超市（上海中心店）",
    date: "2026-06-13",
    amount: 139.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 120,
    category: "餐费",
    description: "美团跑腿",
    date: "2026-06-13",
    amount: 49.8,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 121,
    category: "餐费",
    description: "榭福屋 Meituan-雪味(上海)餐饮管理有限公司",
    date: "2026-06-13",
    amount: 315.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 122,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-陆师傅-06月13日行程",
    date: "2026-06-13",
    amount: 15.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 123,
    category: "交通费",
    description: "滴滴出行 滴滴专车打车-朱师傅-06月13日行程",
    date: "2026-06-13",
    amount: 13.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 124,
    category: "交通费",
    description: "滴滴出行 滴滴打车-杜师傅",
    date: "2026-06-13",
    amount: 28.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 125,
    category: "餐费",
    description: "coffeaSHED-咖啡大棚 coffea SHED",
    date: "2026-06-13",
    amount: 33.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 126,
    category: "餐费",
    description: "美团平台商户 銀蔵ginzo焼鳥 ll 灯隠higura-大众点评买单-大众点评App-260",
    date: "2026-06-13",
    amount: 470.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 127,
    category: "餐费",
    description: "luckin coffee 订单付款",
    date: "2026-06-14",
    amount: 35.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 128,
    category: "餐费",
    description: "上海沃歌斯餐饮有限公司-门店 上海幸福里",
    date: "2026-06-14",
    amount: 330.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 129,
    category: "餐费",
    description: "美团平台商户 南洋記Asian Fusion BistroEatery-大众点评App-260",
    date: "2026-06-14",
    amount: 86.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 130,
    category: "餐费",
    description: "美团平台商户 南洋記Asian Fusion BistroEatery-大众点评App-260",
    date: "2026-06-14",
    amount: 173.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 131,
    category: "餐费",
    description: "南洋记现代东南亚餐酒馆扫码收款",
    date: "2026-06-14",
    amount: 239.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 132,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-乐师傅-06月14日行程",
    date: "2026-06-14",
    amount: 12.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 133,
    category: "餐费",
    description: "上海全家便利店",
    date: "2026-06-14",
    amount: 18.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 134,
    category: "餐费",
    description: "luckin coffee 订单付款",
    date: "2026-06-15",
    amount: 22.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 135,
    category: "餐费",
    description: "luckin coffee 订单付款",
    date: "2026-06-15",
    amount: 11.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 136,
    category: "交通费",
    description: "滴滴出行 滴滴打车-孙师傅",
    date: "2026-06-15",
    amount: 16.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 137,
    category: "餐费",
    description: "CASABAJA上海",
    date: "2026-06-15",
    amount: 389.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 138,
    category: "餐费",
    description: "美团 华氏大药房（总店）",
    date: "2026-06-15",
    amount: 26.96,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 139,
    category: "餐费",
    description: "luckin coffee 订单付款",
    date: "2026-06-16",
    amount: 39.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 140,
    category: "餐费",
    description: "上海沃歌斯餐饮有限公司-门店 上海幸福里",
    date: "2026-06-16",
    amount: 353.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 141,
    category: "餐费",
    description: "東京屋 收款方备注:二维码收款付款方留言:0616 晚饭",
    date: "2026-06-16",
    amount: 492.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 142,
    category: "餐费",
    description: "Siceman Gealto 堂食-spiceman gelato（延平路店）",
    date: "2026-06-16",
    amount: 96.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 143,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-张师傅-06月16日行程",
    date: "2026-06-16",
    amount: 14.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 144,
    category: "住宿费",
    description: "华住酒店集团 全季上海延安路酒店,订单编号:2000521260617102352864006",
    date: "2026-06-17",
    amount: 538.65,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 145,
    category: "餐费",
    description: "FASCINO BAKERY & CAFE FASCINO",
    date: "2026-06-17",
    amount: 121.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 146,
    category: "餐费",
    description: "Omills Light O'MILLS",
    date: "2026-06-17",
    amount: 447.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 147,
    category: "餐费",
    description: "Omills Light O'MILLS",
    date: "2026-06-17",
    amount: 90.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 148,
    category: "其他",
    description: "爱趣平方(上海)宠物有限公司",
    date: "2026-06-17",
    amount: 93.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 149,
    category: "餐费",
    description: "PINK佳品客(上海One ITC店) 订单支付",
    date: "2026-06-17",
    amount: 267.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 150,
    category: "餐费",
    description: "PINK佳品客(上海One ITC店) 订单支付",
    date: "2026-06-17",
    amount: 106.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 151,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-叶师傅-06月16日行程",
    date: "2026-06-18",
    amount: 30.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 152,
    category: "餐费",
    description: "美团 Asap.（咖啡）",
    date: "2026-06-18",
    amount: 75.4,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 153,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-彭师傅-06月18日行程",
    date: "2026-06-18",
    amount: 63.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 154,
    category: "餐费",
    description: "寄畅興·江南蟹黄面（西湖湖畔店） 美团/大众点评点餐订单-061850260558900187905",
    date: "2026-06-18",
    amount: 392.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 155,
    category: "餐费",
    description: "美团平台商户 寄畅興·百年蟹黄面·非遗杭帮菜-大众点评App-2606181110030000",
    date: "2026-06-18",
    amount: 15.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 156,
    category: "餐费",
    description: "寄畅興·江南蟹黄面（西湖湖畔店） 美团/大众点评点餐订单-061850260558915111312",
    date: "2026-06-18",
    amount: 36.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 157,
    category: "交通费",
    description: "滴滴出行 滴滴轻享打车",
    date: "2026-06-18",
    amount: 26.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 158,
    category: "差旅-交通",
    description: "携程 单程杭州北京，赵馨怡",
    date: "2026-06-19",
    amount: 490.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 159,
    category: "交通费",
    description: "滴滴出行 滴滴打车-梅师傅",
    date: "2026-06-19",
    amount: 18.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 160,
    category: "其他",
    description: "小红书",
    date: "2026-06-19",
    amount: 10.98,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 161,
    category: "差旅-交通",
    description: "携程 单程杭州北京，水素",
    date: "2026-06-19",
    amount: 500.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 162,
    category: "差旅-交通",
    description: "携程旅行网 杭州滨江星光大道亚朵酒店",
    date: "2026-06-19",
    amount: 353.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 163,
    category: "差旅-交通",
    description: "携程旅行网 杭州滨江星光大道亚朵酒店",
    date: "2026-06-19",
    amount: 377.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 164,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-徐师傅-06月19日行程",
    date: "2026-06-19",
    amount: 31.8,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 165,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-郁师傅-06月19日行程",
    date: "2026-06-19",
    amount: 23.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 166,
    category: "交通费",
    description: "滴滴出行 滴滴轻享打车",
    date: "2026-06-19",
    amount: 27.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 167,
    category: "餐费",
    description: "醉禾鲜小馆生腌熟醉围炉打边 美团收银909700213867636181",
    date: "2026-06-19",
    amount: 538.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 168,
    category: "餐费",
    description: "美团 teagenius(山泽里店)",
    date: "2026-06-19",
    amount: 57.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 169,
    category: "餐费",
    description: "美团 Pull-Tab拉环咖啡（滨江龙湖天街店）",
    date: "2026-06-20",
    amount: 20.4,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 170,
    category: "餐费",
    description: "美团 Pull-Tab拉环咖啡（滨江龙湖天街店）",
    date: "2026-06-20",
    amount: 22.4,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 171,
    category: "差旅-交通",
    description: "携程 机票改签费用",
    date: "2026-06-20",
    amount: 240.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 172,
    category: "差旅-交通",
    description: "携程 机票改签费用",
    date: "2026-06-20",
    amount: 240.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 173,
    category: "差旅-交通",
    description: "携程 Kio机票，杭州 - 深圳",
    date: "2026-06-20",
    amount: 775.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 174,
    category: "住宿费",
    description: "华住酒店集团 全季杭州西溪湿地花坞地铁站酒店,订单编号:9001084260620144544",
    date: "2026-06-20",
    amount: 523.25,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 175,
    category: "住宿费",
    description: "华住酒店集团 全季杭州西溪湿地花坞地铁站酒店,订单编号:9001084260620144615",
    date: "2026-06-20",
    amount: 468.37,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 176,
    category: "餐费",
    description: "美团 CycleCycle（面包·咖啡·蛋糕·天目里店）",
    date: "2026-06-20",
    amount: 92.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 177,
    category: "交通费",
    description: "杭州西溪湿地运营 自助机售(ZZJ260620161149123698)周家村电",
    date: "2026-06-20",
    amount: 180.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 178,
    category: "交通费",
    description: "滴滴出行 E品出行-打车费用",
    date: "2026-06-20",
    amount: 41.03,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 179,
    category: "餐费",
    description: "美团 【南京大牌档(西溪印象城店)】金陵烤鸭（南京传统名菜）等1…",
    date: "2026-06-20",
    amount: 157.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 180,
    category: "餐费",
    description: "美团 椿花奶奶（江南手工小吃·西溪印象城店）",
    date: "2026-06-20",
    amount: 39.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 181,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-费师傅-06月20日行程",
    date: "2026-06-21",
    amount: 8.8,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 182,
    category: "餐费",
    description: "美团 合德记顺德双皮奶·甜品糖水（乐天城店）",
    date: "2026-06-21",
    amount: 57.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 183,
    category: "餐费",
    description: "杭州九茶茶叶有限公司",
    date: "2026-06-21",
    amount: 4.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 184,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-宋师傅-06月21日行程",
    date: "2026-06-21",
    amount: 38.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 185,
    category: "餐费",
    description: "喜禄杭州中心店",
    date: "2026-06-21",
    amount: 598.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 186,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-唐师傅-06月21日行程",
    date: "2026-06-21",
    amount: 31.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 187,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-廖师傅-06月21日行程",
    date: "2026-06-22",
    amount: 31.4,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 188,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-潘师傅-06月22日行程",
    date: "2026-06-22",
    amount: 48.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 189,
    category: "汽车费用",
    description: "浙江周大福创建公路有限公司 浙江高速：浙江东洲岛站-留下",
    date: "2026-06-22",
    amount: 15.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 190,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-骆师傅-06月22日行程",
    date: "2026-06-22",
    amount: 55.8,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 191,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-汪师傅-06月22日行程",
    date: "2026-06-22",
    amount: 62.8,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  }
];

const tpiaoList = [];
