// 报销单 · 杭州八月堪景 —— 每日花销随发随记
const reportInfo = {
  reportTitle: "报销单 · 杭州八月堪景",
  company: "廿一影视文化传播（上海）有限公司",
  submitter: "水素",
  project: "《竹林遗录》",
  department: "",
  period: "2026年8月（杭州堪景）",
  reportDate: "",
  loan: 100000,
};

const categoryOptions = [
  "堪景覆景器材费", "一般交通（打车）", "勘景车辆", "勘景燃料费", "过路过桥费", "停车费",
  "勘景餐饮", "覆景餐饮", "杂费（水饮/补给/门票）", "酒店", "差旅", "创意阐述", "脚本绘制费", "前期杂支",
];

const expenseItems = [
  {
    id: 1,
    category: "差旅",
    description: "8/9 邱、赵、水三人高铁，北京-杭州",
    date: "2026-08-09",
    amount: 2004,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 中铁网络 12306",
  },
  {
    id: 2,
    category: "杂费（水饮/补给/门票）",
    description: "驱蚊水喷雾 3瓶（堪景户外用）",
    date: "2026-08-09",
    amount: 12.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 1688 绿壹(龙岩)生物技术 订单5127359942201006333，寄杭州桔子酒店前台",
  },
  {
    id: 3,
    category: "杂费（水饮/补给/门票）",
    description: "蕉下户外驱蚊器+3支驱蚊液（堪景户外用）",
    date: "2026-08-09",
    amount: 98.88,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-09_蕉下户外驱蚊器+3支驱蚊液（堪景户外用）_付款截图_实付98.88.png",
    invoiceFiles: ["invoices/extra/2026-08-09_蕉下户外驱蚊器+3支驱蚊液（堪景户外用）_付款截图_实付98.88.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 闲鱼 订单5126173704369015515（二手平台，无发票）",
  },
  {
    id: 4,
    category: "酒店",
    description: "堪景期间酒店住宿（汇总）",
    date: "2026-08-10",
    amount: 4145.2,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-10_堪景酒店住宿两晚_付款截图_1158.10.png",
    invoiceFiles: [
      "invoices/extra/2026-08-10_堪景酒店住宿两晚_付款截图_1158.10.png",
      "invoices/extra/2026-08-10_堪景酒店退款17元_付款截图_17.00.png",
      "invoices/extra/2026-08-12_堪景酒店续住两晚2间_付款截图_1236.10.png",
    ],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 华住酒店集团（桔子杭州文体中心西溪湿地酒店），微信零钱通支付，2间房 3人。8/10-8/12 两晚：573.30 + 584.80 = 1158.10，酒店减免退款 17.00 → 1141.10；8/12-8/14 续住两晚：593.30 + 642.80 = 1236.10；8/14-8/16 两晚 3 间房：958.00（建行卡，已含建行优惠 2.00）；8/16 晚 3 间房：810.00。合计 4145.20。后续堪景酒店费用继续累加到本条。发票到时候一起开",
  },
  {
    id: 5,
    category: "勘景餐饮",
    description: "8/10 水素高铁上午饭",
    date: "2026-08-10",
    amount: 30,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 发票已收到，待整理上传",
  },
  {
    id: 6,
    category: "一般交通（打车）",
    description: "8/10 打车 到高铁站",
    date: "2026-08-10",
    amount: 33.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 打车费，以后整体一起开发票",
  },
  {
    id: 7,
    category: "勘景餐饮",
    description: "8/10 堪景晚饭 3人",
    date: "2026-08-10",
    amount: 126.94,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-10_堪景晚饭3人_付款截图_126.94.png",
    invoiceFiles: ["invoices/extra/2026-08-10_堪景晚饭3人_付款截图_126.94.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团，微信支付。付款截图已存，发票待开",
  },
  {
    id: 8,
    category: "杂费（水饮/补给/门票）",
    description: "堪景补给：饮用水、湿巾、电解质水",
    date: "2026-08-10",
    amount: 80.41,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-10_堪景补给水湿巾电解质水_付款截图_80.41.png",
    invoiceFiles: ["invoices/extra/2026-08-10_堪景补给水湿巾电解质水_付款截图_80.41.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 天猫超市 3件：水 19.89 + 农夫山泉电解质水 50.16 + 得宝湿巾 10.36，共减 68.38 后实付 80.41。可开发票，待开",
  },
  {
    id: 9,
    category: "一般交通（打车）",
    description: "8/10 打车 高铁站-酒店",
    date: "2026-08-10",
    amount: 27.4,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 滴滴，可整合开发票",
  },
  {
    id: 10,
    category: "勘景车辆",
    description: "堪景租车 8/11-8/13（含保险）",
    date: "2026-08-11",
    amount: 387.9,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-11_堪景租车含保险_付款截图_387.90.png",
    invoiceFiles: ["invoices/extra/2026-08-11_堪景租车含保险_付款截图_387.90.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 滴滴租车，微信支付，8/10 下单。费用含保险。付款截图已存，发票待开",
  },
  {
    id: 11,
    category: "勘景餐饮",
    description: "8/11 堪景晚饭 3人",
    date: "2026-08-11",
    amount: 442,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团平台商户，微信零钱通支付。发票待开",
  },
  {
    id: 12,
    category: "停车费",
    description: "8/11 晚饭停车 联合大厦",
    date: "2026-08-11",
    amount: 16,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 停管家-浙M***1D-联合大厦-出口扫码，南都物业服务集团，零钱通 8/11 18:56。交易单号 45000000360202608115591681699。发票待开",
  },
  {
    id: 13,
    category: "杂费（水饮/补给/门票）",
    description: "8/10 买水（美团）",
    date: "2026-08-10",
    amount: 49.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团，微信零钱通支付。发票待开",
  },
  {
    id: 14,
    category: "勘景餐饮",
    description: "8/11 堪景午饭 3人",
    date: "2026-08-11",
    amount: 215,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 扫码付给「乃法」，零钱通 8/11 13:37，付款留言「0811 午饭 三人」。转账单号 10001073012026081101222805234623。发票待开",
  },
  {
    id: 15,
    category: "杂费（水饮/补给/门票）",
    description: "8/11 堪景景点摆渡车票 3人",
    date: "2026-08-11",
    amount: 30,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 杭州长乐林雨堂文化旅游有限公司（长乐林场观光车），零钱通 8/11 16:10。交易单号 45000000319202608111737881630。发票待开",
  },
  {
    id: 16,
    category: "停车费",
    description: "8/11 堪景景点停车费",
    date: "2026-08-11",
    amount: 6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 浙M0K81D-杭州长乐森林公园停车场，杭州长乐林雨堂文化旅游有限公司，零钱通 8/11 16:54。交易单号 45000000316202608113599752683。发票待开",
  },
  {
    id: 17,
    category: "停车费",
    description: "8/11 停车费（绿城停车）",
    date: "2026-08-11",
    amount: 5,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 绿城停车，微信零钱通支付。发票待开",
  },
  {
    id: 18,
    category: "过路过桥费",
    description: "8/11 堪景高速费（杭州都市高速）",
    date: "2026-08-11",
    amount: 29,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 浙江高速：龙门古镇站-仙宅，杭州都市高速公路有限公司，零钱通 8/11 15:55。交易单号 42000003114202608110995659172。发票待开",
  },
  {
    id: 19,
    category: "过路过桥费",
    description: "8/11 堪景高速费（浙江周大福创建公路）",
    date: "2026-08-11",
    amount: 11,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 浙江周大福创建公路，微信零钱通支付。发票待开",
  },
  {
    id: 20,
    category: "勘景餐饮",
    description: "8/12 堪景咖啡",
    date: "2026-08-12",
    amount: 30.52,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-12_堪景咖啡_付款截图_30.52.png",
    invoiceFiles: ["invoices/extra/2026-08-12_堪景咖啡_付款截图_30.52.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团，微信支付。付款截图已存，发票待开",
  },
  {
    id: 21,
    category: "勘景餐饮",
    description: "8/16 早咖啡 2人（SOFTCAFE）",
    date: "2026-08-16",
    amount: 38.6,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-16_堪景咖啡两杯_付款截图_38.60.png",
    invoiceFiles: ["invoices/extra/2026-08-16_堪景咖啡两杯_付款截图_38.60.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团外卖 SOFTCAFE 两单：葡萄冰奶拿铁 19.80 + 栗子金桂拿铁 18.80 = 38.60。发票待开",
  },
  {
    id: 22,
    category: "勘景餐饮",
    description: "8/15 堪景晚饭 3人",
    date: "2026-08-15",
    amount: 132.83,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-15_堪景晚饭3人_付款截图_132.83.png",
    invoiceFiles: ["invoices/extra/2026-08-15_堪景晚饭3人_付款截图_132.83.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团外卖两单：张记肠粉店-广式生滚粥（西溪银泰店）113.10（6件）+ 面总管（西溪天街店）19.73（2件）= 132.83。发票待开",
  },
  {
    id: 23,
    category: "勘景燃料费",
    description: "8/16 堪景加油",
    date: "2026-08-16",
    amount: 305.91,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-16_堪景加油_付款截图_305.91.png",
    invoiceFiles: ["invoices/extra/2026-08-16_堪景加油_付款截图_305.91.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 中国石化销售股份有限公司浙江石油分公司，微信支付。发票待开",
  },
  {
    id: 24,
    category: "勘景餐饮",
    description: "8/16 晚上奶茶 2人",
    date: "2026-08-16",
    amount: 43,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 喜茶，微信零钱通支付。发票待开",
  },
  {
    id: 25,
    category: "勘景餐饮",
    description: "8/16 堪景晚饭 3人",
    date: "2026-08-16",
    amount: 150.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团，微信零钱通支付。发票待开",
  },
  {
    id: 26,
    category: "勘景餐饮",
    description: "8/16 堪景午饭 3人",
    date: "2026-08-16",
    amount: 43,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 扫码付给「小伊」，零钱通，付款留言「0816 午饭 3人」。发票待开",
  },
  {
    id: 27,
    category: "停车费",
    description: "8/16 堪景景点停车费",
    date: "2026-08-16",
    amount: 6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 杭州长乐林雨堂文化旅游有限公司，微信零钱通支付。发票待开",
  },
  {
    id: 28,
    category: "杂费（水饮/补给/门票）",
    description: "8/16 堪景景点观光车票 3人",
    date: "2026-08-16",
    amount: 30,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 长乐林场观光车（林雨堂），微信零钱通支付。发票待开",
  },
  {
    id: 29,
    category: "勘景餐饮",
    description: "8/15 晚奶茶 2人",
    date: "2026-08-15",
    amount: 44,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 喜茶，微信零钱通支付。发票待开",
  },
  {
    id: 30,
    category: "勘景餐饮",
    description: "8/15 夜宵 3人",
    date: "2026-08-15",
    amount: 43.4,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团，微信余额支付。发票待开",
  },
  {
    id: 31,
    category: "过路过桥费",
    description: "8/15 堪景高速费（浙江杭徽高速）",
    date: "2026-08-15",
    amount: 23,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 浙江杭徽高速公路，微信零钱通支付。发票待开",
  },
  {
    id: 32,
    category: "杂费（水饮/补给/门票）",
    description: "8/15 堪景门票 3人",
    date: "2026-08-15",
    amount: 174,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 携程旅行网，微信零钱通支付。发票待开",
  },
  {
    id: 33,
    category: "过路过桥费",
    description: "8/15 堪景高速费（杭州都市高速）",
    date: "2026-08-15",
    amount: 23,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 杭州都市高速公路，微信零钱通支付。与 id31（浙江杭徽高速 23.00）是同日不同收费公司的两笔，非重复。发票待开",
  },
  {
    id: 34,
    category: "勘景餐饮",
    description: "8/15 堪景午饭 3人",
    date: "2026-08-15",
    amount: 50,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 扫码付给「玉姐果蔬凉皮」，零钱通，付款留言「0815 午饭 3人」。发票待开",
  },
  {
    id: 35,
    category: "勘景餐饮",
    description: "8/15 早饭咖啡",
    date: "2026-08-15",
    amount: 42.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团，微信零钱通支付。发票待开",
  },
  {
    id: 36,
    category: "勘景餐饮",
    description: "8/14 堪景晚饭 3人",
    date: "2026-08-14",
    amount: 93.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团，微信余额支付。发票待开",
  },
];

const tpiaoList = [];
