// 报销单 · TIFF 多伦多电影节 —— 境外行程花销，随发随记（即黑豆加拿大 travel，威姐 sponsor）
// 外币：amount 填折算后的人民币，原币金额和汇率写进 remark（如「CAD 45.00 @4.95」）
const reportInfo = {
  reportTitle: "报销单 · TIFF 多伦多电影节",
  company: "廿一影视文化传播（上海）有限公司",
  submitter: "水素",
  project: "《竹林遗录》",
  department: "",
  period: "TIFF（多伦多电影节）",
  reportDate: "",
  loan: 0,
};

const categoryOptions = [
  "国际机票", "签证费", "保险", "住宿费", "境外市内交通", "餐费",
  "电影节报名费", "展会/活动费", "宣传物料", "业务招待费",
  "通讯费（境外流量）", "办公用品", "快递费", "其他",
];

const expenseItems = [
  {
    id: 1,
    category: "住宿费",
    description: "AIRBNB HM9FP83FSW",
    date: "2026-08-28",
    amount: 5104.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 760.66 @6.7101（Amex）；Airbnb 均为加拿大住宿（你确认）",
  },
  {
    id: 2,
    category: "住宿费",
    description: "AIRBNB HM2FP3REK8",
    date: "2026-09-03",
    amount: 24239.77,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 3612.43 @6.7101（Amex）；Airbnb 均为加拿大住宿（你确认）",
  },
  {
    id: 3,
    category: "展会/活动费",
    description: "TORONTO INTERNATIONAL, Toronto",
    date: "2026-09-03",
    amount: 1109.85,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 165.40 @6.7101（Amex）；疑似 TIFF",
  },
  {
    id: 4,
    category: "国际机票",
    description: "微信转账 — 色珍机票 去程 拉萨→北京（西藏航空 TV9749）",
    date: "2026-09-03",
    amount: 2418,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "人民币支付；给导演报销；航班 9/6；付款日按起飞前三天记",
  },
  {
    id: 5,
    category: "国际机票",
    description: "色珍机票 去程 北京→多伦多（UA889/UA1806）",
    date: "2026-09-05",
    amount: 7346,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "人民币支付；给导演报销；航班 9/8；付款日按起飞前三天记",
  },
  {
    id: 6,
    category: "餐费",
    description: "00 GELATO, Toronto",
    date: "2026-09-12",
    amount: 37.04,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 5.52 @6.7101（Amex）",
  },
  {
    id: 7,
    category: "餐费",
    description: "IKKOUSHA RAMEN, Toronto",
    date: "2026-09-12",
    amount: 238.48,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 35.54 @6.7101（Amex）",
  },
  {
    id: 8,
    category: "展会/活动费",
    description: "TORONTO INTL FILM (TIFF)",
    date: "2026-09-12",
    amount: 65.76,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 9.80 @6.7101（Amex）",
  },
  {
    id: 9,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-12",
    amount: 70.39,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 10.49 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 10,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-12",
    amount: 334.77,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 49.89 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 11,
    category: "展会/活动费",
    description: "Tor Intl Film Festival",
    date: "2026-09-12",
    amount: 373.55,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 55.67 @6.7101（Apple Card）",
  },
  {
    id: 12,
    category: "通讯费（境外流量）",
    description: "nomadesim.com",
    date: "2026-09-12",
    amount: 192.92,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 28.75 @6.7101（Apple Card）；境外 eSIM（你确认归加拿大）",
  },
  {
    id: 13,
    category: "餐费",
    description: "FOUND COFFEE, Toronto",
    date: "2026-09-13",
    amount: 42.47,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 6.33 @6.7101（Amex）",
  },
  {
    id: 14,
    category: "餐费",
    description: "UBER EATS, Toronto",
    date: "2026-09-13",
    amount: 307.93,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 45.89 @6.7101（Amex）",
  },
  {
    id: 15,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-13",
    amount: 34.09,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 5.08 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 16,
    category: "餐费",
    description: "NONNI CAFE, Toronto",
    date: "2026-09-14",
    amount: 88.51,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 13.19 @6.7101（Amex）",
  },
  {
    id: 17,
    category: "餐费",
    description: "NONNI CAFE, Toronto",
    date: "2026-09-14",
    amount: 141.99,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 21.16 @6.7101（Amex）",
  },
  {
    id: 18,
    category: "展会/活动费",
    description: "PRINCESS OF WALES, Toronto",
    date: "2026-09-14",
    amount: 21.74,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 3.24 @6.7101（Amex）",
  },
  {
    id: 19,
    category: "餐费",
    description: "ORETTA, Toronto",
    date: "2026-09-14",
    amount: 94.01,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 14.01 @6.7101（Amex）",
  },
  {
    id: 20,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-14",
    amount: 49.39,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 7.36 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 21,
    category: "餐费",
    description: "BEVY@COMBINE, Toronto",
    date: "2026-09-15",
    amount: 34.42,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 5.13 @6.7101（Amex）",
  },
  {
    id: 22,
    category: "其他",
    description: "L DERACH (CANADA), Toronto",
    date: "2026-09-15",
    amount: 748.85,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 111.60 @6.7101（Amex）；Läderach 巧克力，类目待确认",
  },
  {
    id: 23,
    category: "餐费",
    description: "SOUTH ST. BURGER, Toronto",
    date: "2026-09-15",
    amount: 58.85,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 8.77 @6.7101（Amex）",
  },
  {
    id: 24,
    category: "展会/活动费",
    description: "TORONTO INTL FILM (TIFF)",
    date: "2026-09-15",
    amount: 1525.07,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 227.28 @6.7101（Amex）",
  },
  {
    id: 25,
    category: "餐费",
    description: "SISTER SI…, Toronto",
    date: "2026-09-15",
    amount: 43.75,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 6.52 @6.7101（Amex）",
  },
  {
    id: 26,
    category: "餐费",
    description: "SISTER SI…, Toronto",
    date: "2026-09-15",
    amount: 110.72,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 16.50 @6.7101（Amex）",
  },
  {
    id: 27,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-15",
    amount: 28.85,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 4.30 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 28,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-15",
    amount: 68.51,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 10.21 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 29,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-15",
    amount: 102.46,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 15.27 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 30,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-15",
    amount: 103.54,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 15.43 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 31,
    category: "住宿费",
    description: "AIRBNB HM3F3WCBXN",
    date: "2026-09-16",
    amount: 4817.65,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 717.97 @6.7101（Amex）；Airbnb 均为加拿大住宿（你确认）",
  },
  {
    id: 32,
    category: "餐费",
    description: "NONNI CAFE, Toronto",
    date: "2026-09-16",
    amount: 82.67,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 12.32 @6.7101（Amex）",
  },
  {
    id: 33,
    category: "餐费",
    description: "NONNI CAFE, Toronto",
    date: "2026-09-16",
    amount: 102.06,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 15.21 @6.7101（Amex）",
  },
  {
    id: 34,
    category: "餐费",
    description: "PIZZERIA MORETTI, Toronto",
    date: "2026-09-16",
    amount: 167.69,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 24.99 @6.7101（Amex）",
  },
  {
    id: 35,
    category: "餐费",
    description: "KHAO SAN, Toronto",
    date: "2026-09-16",
    amount: 581.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 86.69 @6.7101（Amex）",
  },
  {
    id: 36,
    category: "餐费",
    description: "UBER EATS, Toronto",
    date: "2026-09-16",
    amount: 330.74,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 49.29 @6.7101（Amex）",
  },
  {
    id: 37,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-16",
    amount: 29.12,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 4.34 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 38,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-16",
    amount: 53.48,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 7.97 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 39,
    category: "餐费",
    description: "HEYTEA 喜茶, Toronto",
    date: "2026-09-16",
    amount: 174.01,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "人民币支付；微信账单误标「服饰」，实为多伦多喜茶；人民币支付",
  },
  {
    id: 40,
    category: "住宿费",
    description: "AIRBNB * INC",
    date: "2026-09-17",
    amount: 301.95,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 45.00 @6.7101（Amex）；Airbnb 均为加拿大住宿（你确认）",
  },
  {
    id: 41,
    category: "餐费",
    description: "BEVY@COMBINE, Toronto",
    date: "2026-09-17",
    amount: 29.99,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 4.47 @6.7101（Amex）",
  },
  {
    id: 42,
    category: "餐费",
    description: "FOUND COFFEE, Toronto",
    date: "2026-09-17",
    amount: 43.55,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 6.49 @6.7101（Amex）",
  },
  {
    id: 43,
    category: "餐费",
    description: "KING FRESH FOOD, Toronto",
    date: "2026-09-17",
    amount: 173.12,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 25.80 @6.7101（Amex）",
  },
  {
    id: 44,
    category: "餐费",
    description: "UBER EATS, Toronto",
    date: "2026-09-17",
    amount: 145.81,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 21.73 @6.7101（Amex）",
  },
  {
    id: 45,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-17",
    amount: 6.71,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 1.00 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 46,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-17",
    amount: 43.41,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 6.47 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 47,
    category: "餐费",
    description: "Ka Chi Korean Restaura",
    date: "2026-09-17",
    amount: 542.98,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 80.92 @6.7101（Apple Card）",
  },
  {
    id: 48,
    category: "餐费",
    description: "BEVY@COMBINE, Toronto",
    date: "2026-09-18",
    amount: 49.39,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 7.36 @6.7101（Amex）",
  },
  {
    id: 49,
    category: "餐费",
    description: "BUTTER BAKER, Toronto",
    date: "2026-09-18",
    amount: 38.45,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 5.73 @6.7101（Amex）",
  },
  {
    id: 50,
    category: "餐费",
    description: "MIZUNARA INC., Toronto",
    date: "2026-09-18",
    amount: 601.09,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 89.58 @6.7101（Amex）",
  },
  {
    id: 51,
    category: "展会/活动费",
    description: "ROYAL ALEXANDRA, Toronto",
    date: "2026-09-18",
    amount: 81.46,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 12.14 @6.7101（Amex）",
  },
  {
    id: 52,
    category: "餐费",
    description: "FIGO, Toronto",
    date: "2026-09-18",
    amount: 714.36,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 106.46 @6.7101（Amex）",
  },
  {
    id: 53,
    category: "展会/活动费",
    description: "PAYPAL *TICKETMASTER (780 区号)",
    date: "2026-09-18",
    amount: 294.91,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 43.95 @6.7101（Amex）；疑似 Ticketmaster 加拿大，推定",
  },
  {
    id: 54,
    category: "餐费",
    description: "UBER EATS, Toronto",
    date: "2026-09-18",
    amount: 232.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 34.59 @6.7101（Amex）",
  },
  {
    id: 55,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-18",
    amount: 43.41,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 6.47 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 56,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-18",
    amount: 48.58,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 7.24 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 57,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-18",
    amount: 111.66,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 16.64 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 58,
    category: "餐费",
    description: "Small Pot Restaurant (",
    date: "2026-09-18",
    amount: 219.96,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 32.78 @6.7101（Apple Card）",
  },
  {
    id: 59,
    category: "住宿费",
    description: "AIRBNB HM3F3WCBXN（退款）",
    date: "2026-09-19",
    amount: -224.12,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD -33.40 @6.7101（Amex）；退款；Airbnb 均为加拿大住宿（你确认）",
  },
  {
    id: 60,
    category: "国际机票",
    description: "AIR CANADA, Toronto",
    date: "2026-09-19",
    amount: 226.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 33.77 @6.7101（Amex）；小额，疑似行李/选座费",
  },
  {
    id: 61,
    category: "国际机票",
    description: "AIR CANADA, Toronto",
    date: "2026-09-19",
    amount: 302.16,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 45.03 @6.7101（Amex）；小额，疑似行李/选座费",
  },
  {
    id: 62,
    category: "餐费",
    description: "ISLAND MARKET, Toronto",
    date: "2026-09-19",
    amount: 32.48,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 4.84 @6.7101（Amex）",
  },
  {
    id: 63,
    category: "餐费",
    description: "YTZ PILOT COFFEE, Toronto",
    date: "2026-09-19",
    amount: 36.84,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 5.49 @6.7101（Amex）",
  },
  {
    id: 64,
    category: "餐费",
    description: "UBER EATS, Toronto",
    date: "2026-09-19",
    amount: 130.78,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 19.49 @6.7101（Amex）",
  },
  {
    id: 65,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-19",
    amount: 38.72,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 5.77 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 66,
    category: "境外市内交通",
    description: "UBER",
    date: "2026-09-19",
    amount: 67.84,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 10.11 @6.7101（Amex）；无地点；按在多伦多期间推定",
  },
  {
    id: 67,
    category: "国际机票",
    description: "微信转账 — 色珍机票 回程 多伦多→拉萨",
    date: "",
    amount: 6845,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "人民币支付；给导演报销；人民币支付；日期待补",
  },
  {
    id: 68,
    category: "国际机票",
    description: "水素 机票 北京→多伦多（Expedia）",
    date: "",
    amount: 10641.55,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "USD 1585.90 @6.7101（MasterCard）；手动添加；MasterCard 9881 支付，不在 Amex 账单里；日期待补",
  },
];

const tpiaoList = [];
