// ============================================================
// 报销单 · 堪景贵州山东（5月） —— 由微信流水自动生成，发票状态待对应
// 发票文件放在 invoices/kanjing/ 下
// ============================================================

const reportInfo = {
  reportTitle: "报销单 · 堪景贵州山东（5月）",
  submitter: "水素",
  department: "",
  period: "2026年5月（堪景 贵州+山东）",
  reportDate: "2026-07-03",
};

const categoryOptions = [
  "交通费", "差旅-交通", "住宿费", "餐费", "汽车费用", "快递费", "办公用品", "业务招待费", "其他",
];

const expenseItems = [
  {
    id: 1,
    category: "差旅-交通",
    description: "携程 单程机票北京贵阳",
    date: "2026-05-18",
    amount: 1520.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 2,
    category: "差旅-交通",
    description: "携程 单程机票北京贵阳",
    date: "2026-05-18",
    amount: 760.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 3,
    category: "差旅-交通",
    description: "携程 单程南京贵阳",
    date: "2026-05-18",
    amount: 670.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 4,
    category: "其他",
    description: "朱媛 收款方备注:二维码收款付款方留言:portra 160 /45一盒+ HP5/45 两盒",
    date: "2026-05-19",
    amount: 1710.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 5,
    category: "住宿费",
    description: "贵州凯希尼酒店管理有限公司",
    date: "2026-05-20",
    amount: 280.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 6,
    category: "餐费",
    description: "美团 去茶山（美的悦然时光店·咖啡·鲜奶茶·果茶）",
    date: "2026-05-20",
    amount: 73.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 7,
    category: "餐费",
    description: "美团 贞丰糯米饭（会展城店）",
    date: "2026-05-20",
    amount: 40.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 8,
    category: "餐费",
    description: "美团 Jillys Coffee茶几里（虎门巷店）",
    date: "2026-05-21",
    amount: 15.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 9,
    category: "餐费",
    description: "美团 Jillys Coffee茶几里（虎门巷店）",
    date: "2026-05-21",
    amount: 15.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 10,
    category: "餐费",
    description: "美团 Jillys Coffee茶几里（虎门巷店）",
    date: "2026-05-21",
    amount: 23.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 11,
    category: "餐费",
    description: "蒋家肠旺面",
    date: "2026-05-21",
    amount: 63.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 12,
    category: "其他",
    description: "周菊珍 /",
    date: "2026-05-21",
    amount: 93.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 13,
    category: "餐费",
    description: "孟关牛牛顺鲜牛馆 收款方备注:二维码收款付款方留言:0521晚饭",
    date: "2026-05-21",
    amount: 290.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 14,
    category: "餐费",
    description: "美团 喜三德甜品·糖水（冰浆·金融城店）",
    date: "2026-05-21",
    amount: 26.68,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 15,
    category: "餐费",
    description: "K 凯辉 10648大关3店",
    date: "2026-05-21",
    amount: 44.52,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 16,
    category: "住宿费",
    description: "贵州凯希尼酒店管理有限公司",
    date: "2026-05-21",
    amount: 280.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 17,
    category: "住宿费",
    description: "贵州凯希尼酒店管理有限公司",
    date: "2026-05-22",
    amount: 280.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 18,
    category: "餐费",
    description: "美团 25Gahwa（咖瓦咖啡面包）",
    date: "2026-05-22",
    amount: 16.900000000000002,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 19,
    category: "餐费",
    description: "美团 25Gahwa（咖瓦咖啡面包）",
    date: "2026-05-22",
    amount: 20.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 20,
    category: "餐费",
    description: "美团 25Gahwa（咖瓦咖啡面包）",
    date: "2026-05-22",
    amount: 18.59,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 21,
    category: "差旅-交通",
    description: "文荣粉面馆 贵阳观山湖文荣餐饮店",
    date: "2026-05-22",
    amount: 52.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 22,
    category: "餐费",
    description: "清宇便利店-送货到家 收款方备注:二维码收款付款方留言:05/22 午饭便利店零食水",
    date: "2026-05-22",
    amount: 67.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 23,
    category: "餐费",
    description: "美团 抹山序（甲秀楼店）",
    date: "2026-05-22",
    amount: 39.300000000000004,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 24,
    category: "差旅-交通",
    description: "贵阳云岩刘丽军火锅店",
    date: "2026-05-22",
    amount: 305.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 25,
    category: "餐费",
    description: "羊城西饼民生路店-消费",
    date: "2026-05-22",
    amount: 95.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 26,
    category: "餐费",
    description: "骆三姐土豆片店内购物",
    date: "2026-05-22",
    amount: 20.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 27,
    category: "其他",
    description: "辣辣辣里辣 转账备注:濕巾水",
    date: "2026-05-22",
    amount: 28.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 28,
    category: "差旅-交通",
    description: "携程旅行网 都匀港龙大酒店都匀石板古街店",
    date: "2026-05-22",
    amount: 84.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 29,
    category: "差旅-交通",
    description: "携程旅行网 都匀港龙大酒店都匀石板古街店",
    date: "2026-05-22",
    amount: 187.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 30,
    category: "差旅-交通",
    description: "携程旅行网 都匀港龙大酒店都匀石板古街店",
    date: "2026-05-22",
    amount: 172.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 31,
    category: "餐费",
    description: "美团 CaptainGeorge乔治队长(文昌店)",
    date: "2026-05-23",
    amount: 72.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 32,
    category: "餐费",
    description: "荭龄便利店 0523 午饭",
    date: "2026-05-23",
    amount: 27.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 33,
    category: "快递费",
    description: "德邦快递-DPK202747902521",
    date: "2026-05-23",
    amount: 41.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 34,
    category: "餐费",
    description: "廖桂英 收款方备注:二维码收款付款方留言:0523 晚饭",
    date: "2026-05-23",
    amount: 238.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 35,
    category: "餐费",
    description: "美团订单-26052311100300001306523700966830",
    date: "2026-05-23",
    amount: 91.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 36,
    category: "餐费",
    description: "CHAGEE霸王茶姬（贵州黔南都匀市星乐城店）",
    date: "2026-05-23",
    amount: 47.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 37,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-贾师傅-05月20日行程",
    date: "2026-05-23",
    amount: 127.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 38,
    category: "餐费",
    description: "美团 库迪咖啡(都匀万达广场店)",
    date: "2026-05-24",
    amount: 22.900000000000002,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 39,
    category: "餐费",
    description: "美团 库迪咖啡(都匀万达广场店)",
    date: "2026-05-24",
    amount: 15.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 40,
    category: "交通费",
    description: "滴滴出行 滴滴打车-尹师傅",
    date: "2026-05-24",
    amount: 8.01,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 41,
    category: "餐费",
    description: "老苹果 收款方备注:二维码收款付款方留言:0524早飯",
    date: "2026-05-24",
    amount: 39.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 42,
    category: "差旅-交通",
    description: "携程旅行网 白玉兰酒店（泰山景区岱庙店）",
    date: "2026-05-24",
    amount: 330.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 43,
    category: "差旅-交通",
    description: "携程旅行网 凯亚德酒店贵阳龙洞堡机场砂之船奥特莱斯店",
    date: "2026-05-24",
    amount: 138.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 44,
    category: "差旅-交通",
    description: "携程旅行网 白玉兰酒店（泰山景区岱庙店）",
    date: "2026-05-24",
    amount: 330.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 45,
    category: "差旅-交通",
    description: "携程旅行网 凯亚德酒店贵阳龙洞堡机场砂之船奥特莱斯店",
    date: "2026-05-24",
    amount: 128.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 46,
    category: "餐费",
    description: "美团 去茶山（国贸新印1950店·咖啡·鲜奶茶·果茶）",
    date: "2026-05-24",
    amount: 74.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 47,
    category: "餐费",
    description: "听涛拍岸 转账备注:0524 晚飯",
    date: "2026-05-24",
    amount: 295.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 48,
    category: "差旅-交通",
    description: "Lexie 找馨yi 1104 转账备注:机票贵阳-济南 报销",
    date: "2026-05-24",
    amount: 2445.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 49,
    category: "餐费",
    description: "美团 ZOONANA首尔炸鸡（太升国际店）",
    date: "2026-05-24",
    amount: 43.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 50,
    category: "餐费",
    description: "美团 首杨水果（首钢二店）",
    date: "2026-05-24",
    amount: 43.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 51,
    category: "差旅-交通",
    description: "去茶山 【堂食】_贵阳机场店T3航站楼（安检内）_267945",
    date: "2026-05-25",
    amount: 95.60000000000001,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 52,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,",
    date: "2026-05-25",
    amount: 242.65,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 53,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,",
    date: "2026-05-25",
    amount: 271.15,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 54,
    category: "餐费",
    description: "美团 711便利店（诚基中心店）",
    date: "2026-05-25",
    amount: 319.83,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "已扣退款¥21.00",
  },
  {
    id: 55,
    category: "餐费",
    description: "美团 名创优品24小时超级店（济南诚基中心店）",
    date: "2026-05-25",
    amount: 65.82000000000001,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 56,
    category: "餐费",
    description: "美团 松鼠便利（山师店）",
    date: "2026-05-25",
    amount: 74.94,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 57,
    category: "餐费",
    description: "美团 松鼠便利（窑头店）",
    date: "2026-05-25",
    amount: 59.93,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 58,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,",
    date: "2026-05-26",
    amount: 261.15,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 59,
    category: "餐费",
    description: "luckin coffee 订单付款",
    date: "2026-05-26",
    amount: 35.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 60,
    category: "餐费",
    description: "晋同源兰悦中心店订单",
    date: "2026-05-26",
    amount: 57.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 61,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,",
    date: "2026-05-26",
    amount: 279.65,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 62,
    category: "交通费",
    description: "滴滴出行 滴滴快车打车-朱师傅-05月26日行程",
    date: "2026-05-26",
    amount: 27.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 63,
    category: "餐费",
    description: "美团 暖燕·姨妈热饮·现炖燕窝(山师店)",
    date: "2026-05-26",
    amount: 31.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 64,
    category: "餐费",
    description: "美团 北京同仁堂（历山店）",
    date: "2026-05-26",
    amount: 27.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 65,
    category: "餐费",
    description: "美团 【元神御金汤】百合虫草花炖鲜鸡汤等10件商品",
    date: "2026-05-26",
    amount: 121.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 66,
    category: "餐费",
    description: "美团 【Street Shark（山师店）】美式经典芝士牛堡  …",
    date: "2026-05-26",
    amount: 144.01,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 67,
    category: "其他",
    description: "辣辣辣里辣 转账备注:微信转账",
    date: "2026-05-26",
    amount: 213.51999999999998,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 68,
    category: "餐费",
    description: "美团 松鼠便利（窑头店）",
    date: "2026-05-26",
    amount: 41.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 69,
    category: "餐费",
    description: "美团 松鼠便利（窑头店）",
    date: "2026-05-26",
    amount: 38.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 70,
    category: "餐费",
    description: "美团 711便利店（济南山师大北门店）",
    date: "2026-05-26",
    amount: 76.58,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 71,
    category: "餐费",
    description: "美团 WE LUCKY COFFEE现磨咖啡果茶（山大北路店）",
    date: "2026-05-27",
    amount: 52.59,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 72,
    category: "其他",
    description: "山东丝路灵岩文化旅游有限公司运",
    date: "2026-05-27",
    amount: 134.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 73,
    category: "其他",
    description: "京东-订单编号3511486014052261",
    date: "2026-05-27",
    amount: 269.02,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 74,
    category: "交通费",
    description: "滴滴出行 订单费用",
    date: "2026-05-27",
    amount: 45.28,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 75,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-燕师傅-05月27日行程",
    date: "2026-05-27",
    amount: 8.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 76,
    category: "餐费",
    description: "美团 喜茶(泰安金桥城店)",
    date: "2026-05-27",
    amount: 70.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 77,
    category: "餐费",
    description: "美团 松鼠便利（泰安万达店）",
    date: "2026-05-27",
    amount: 58.52,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 78,
    category: "餐费",
    description: "美团 好想来品牌零食（泰安泰山区东湖公园店）",
    date: "2026-05-27",
    amount: 34.47,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 79,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-许师傅-05月27日行程",
    date: "2026-05-28",
    amount: 7.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 80,
    category: "餐费",
    description: "美团 肯悦咖啡（泰安银座店）",
    date: "2026-05-28",
    amount: 67.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 81,
    category: "餐费",
    description: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 82,
    category: "餐费",
    description: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
    date: "2026-05-28",
    amount: 36.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 83,
    category: "餐费",
    description: "无人售货机 盛马售货机仅售2999元-外星人电解质水外星人电解质水外星人...",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 84,
    category: "餐费",
    description: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 85,
    category: "餐费",
    description: "泰安市可栗香",
    date: "2026-05-28",
    amount: 40.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 86,
    category: "餐费",
    description: "沪上阿姨 【堂食】_泰安泰山景区店_61318_37090204247",
    date: "2026-05-28",
    amount: 57.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 87,
    category: "餐费",
    description: "昌盛快餐 /",
    date: "2026-05-28",
    amount: 196.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 88,
    category: "其他",
    description: "Lexie 找馨yi 1104 转账备注:堪景备用金",
    date: "2026-05-28",
    amount: 5000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 89,
    category: "住宿费",
    description: "华住酒店集团 桔子济南文化东路酒店,",
    date: "2026-05-28",
    amount: 525.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 90,
    category: "差旅-交通",
    description: "中铁网络 12306消费",
    date: "2026-05-28",
    amount: 223.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 91,
    category: "交通费",
    description: "滴滴出行 特惠快车打车-刘师傅-05月28日行程",
    date: "2026-05-28",
    amount: 174.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 92,
    category: "其他",
    description: "转账备注:贵州都匀堪景报销-杨天奇",
    date: "2026-05-31",
    amount: 3465.0699999999997,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 93,
    category: "其他",
    description: "杨天奇 转账备注:堪景红包🧧",
    date: "2026-05-31",
    amount: 5000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 94,
    category: "办公用品",
    description: "枪枪影视-器材租赁部 枪枪影视-器材租赁部 转账备注:5月20–29日10天器材租赁费用",
    date: "2026-06-02",
    amount: 2000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  }
];

const tpiaoList = [];
