// 报销单 · 杭州八月堪景 —— 每日花销随发随记
const reportInfo = {
  reportTitle: "报销单 · 杭州八月堪景",
  company: "廿一影视文化传播（上海）有限公司",
  submitter: "水素",
  project: "《竹林遗录》",
  department: "",
  period: "2026年8月（杭州堪景）",
  reportDate: "",
  loan: 100000,
};

const categoryOptions = [
  "堪景覆景器材费", "一般交通（打车）", "勘景车辆", "勘景燃料费", "过路过桥费", "停车费",
  "勘景餐饮", "覆景餐饮", "杂费（水饮/补给/门票）", "酒店", "差旅", "创意阐述", "脚本绘制费", "前期杂支",
];

const expenseItems = [
  {
    id: 1,
    category: "差旅",
    description: "8/9 邱、赵、水三人高铁，北京-杭州",
    date: "2026-08-09",
    amount: 2004,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 中铁网络 12306",
  },
  {
    id: 2,
    category: "杂费（水饮/补给/门票）",
    description: "驱蚊水喷雾 3瓶（堪景户外用）",
    date: "2026-08-09",
    amount: 12.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 1688 绿壹(龙岩)生物技术 订单5127359942201006333，寄杭州桔子酒店前台",
  },
  {
    id: 3,
    category: "杂费（水饮/补给/门票）",
    description: "蕉下户外驱蚊器+3支驱蚊液（堪景户外用）",
    date: "2026-08-09",
    amount: 98.88,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-09_蕉下户外驱蚊器+3支驱蚊液（堪景户外用）_付款截图_实付98.88.png",
    invoiceFiles: ["invoices/extra/2026-08-09_蕉下户外驱蚊器+3支驱蚊液（堪景户外用）_付款截图_实付98.88.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 闲鱼 订单5126173704369015515（二手平台，无发票）",
  },
  {
    id: 4,
    category: "酒店",
    description: "堪景期间酒店住宿（汇总）",
    date: "2026-08-10",
    amount: 1158.1,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-10_堪景酒店住宿两晚_付款截图_1158.10.png",
    invoiceFiles: ["invoices/extra/2026-08-10_堪景酒店住宿两晚_付款截图_1158.10.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 华住酒店集团，微信零钱通支付。8/10-8/12 两晚 2间房 3人：573.30 + 584.80 = 1158.10。后续堪景酒店费用继续累加到本条。发票到时候一起开",
  },
  {
    id: 5,
    category: "勘景餐饮",
    description: "8/10 水素高铁上午饭",
    date: "2026-08-10",
    amount: 30,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 发票已收到，待整理上传",
  },
  {
    id: 6,
    category: "一般交通（打车）",
    description: "8/10 打车 到高铁站",
    date: "2026-08-10",
    amount: 33.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 打车费，以后整体一起开发票",
  },
  {
    id: 7,
    category: "勘景餐饮",
    description: "8/10 堪景晚饭 3人",
    date: "2026-08-10",
    amount: 126.94,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-10_堪景晚饭3人_付款截图_126.94.png",
    invoiceFiles: ["invoices/extra/2026-08-10_堪景晚饭3人_付款截图_126.94.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 美团，微信支付。付款截图已存，发票待开",
  },
  {
    id: 8,
    category: "杂费（水饮/补给/门票）",
    description: "堪景补给：饮用水、湿巾、电解质水",
    date: "2026-08-10",
    amount: 80.41,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-10_堪景补给水湿巾电解质水_付款截图_80.41.png",
    invoiceFiles: ["invoices/extra/2026-08-10_堪景补给水湿巾电解质水_付款截图_80.41.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 天猫超市 3件：水 19.89 + 农夫山泉电解质水 50.16 + 得宝湿巾 10.36，共减 68.38 后实付 80.41。可开发票，待开",
  },
  {
    id: 9,
    category: "一般交通（打车）",
    description: "8/10 打车 高铁站-酒店",
    date: "2026-08-10",
    amount: 27.4,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 滴滴，可整合开发票",
  },
  {
    id: 10,
    category: "汽车费用",
    description: "堪景租车 8/11-8/13（含保险）",
    date: "2026-08-11",
    amount: 387.9,
    voucherType: "invoice",
    invoiceFile: "invoices/extra/2026-08-11_堪景租车含保险_付款截图_387.90.png",
    invoiceFiles: ["invoices/extra/2026-08-11_堪景租车含保险_付款截图_387.90.png"],
    invoiceCategory: "",
    invoiceAmount: "",
    tpiaoIds: [],
    remark: "[水素] 滴滴租车，微信支付，8/10 下单。费用含保险。付款截图已存，发票待开",
  },
];

const tpiaoList = [];
