// ============================================================
// 报销单 · 堪景贵州山东（5月）—— 已按飞书协同版更新
// 用途来自飞书「项目」列，住宿等已按几间/几晚合并，商户放在备注。
// ============================================================

const reportInfo = {
  reportTitle: "报销单 · 堪景贵州山东（5月）",
  submitter: "水素",
  department: "",
  period: "2026年5月（堪景 贵州+山东）",
  reportDate: "2026-07-07",
};

const categoryOptions = [
  "交通费", "差旅-交通", "住宿费", "餐费", "汽车费用", "快递费", "办公用品", "器材", "业务招待费", "其他",
];

const expenseItems = [
  {
    id: 1,
    category: "差旅-交通",
    description: "kio机票，北京-贵阳",
    date: "2026-05-18",
    amount: 1520.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "携程 单程机票北京贵阳",
  },
  {
    id: 2,
    category: "差旅-交通",
    description: "水素机票，北京贵阳",
    date: "2026-05-18",
    amount: 760.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "携程 单程机票北京贵阳",
  },
  {
    id: 3,
    category: "差旅-交通",
    description: "lexie机票，南京贵阳",
    date: "2026-05-18",
    amount: 670.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "携程 单程南京贵阳",
  },
  {
    id: 4,
    category: "差旅-交通",
    description: "贵阳 - 济南机票，kio水素lexie",
    date: "2026-05-24",
    amount: 2445.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-002.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    tpiaoIds: [],
    remark: "Lexie 找馨yi 1104 转账备注:机票贵阳-济南 报销",
  },
  {
    id: 5,
    category: "器材",
    description: "堪景胶片",
    date: "2026-05-19",
    amount: 1710.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "朱媛 收款方备注:二维码收款付款方留言:portra 160 /45一盒+ HP5/45 两盒",
  },
  {
    id: 6,
    category: "住宿费",
    description: "5/20 - 5/22贵阳住宿，两间房",
    date: "2026-05-20",
    amount: 840.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-004.pdf",
    invoiceFiles: [],
    invoiceCategory: "住宿费",
    tpiaoIds: [],
    remark: "贵州凯希尼酒店管理有限公司",
  },
  {
    id: 7,
    category: "住宿费",
    description: "5/23都匀住宿，三间",
    date: "2026-05-22",
    amount: 443.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "携程旅行网 都匀港龙大酒店都匀石板古街店",
  },
  {
    id: 8,
    category: "住宿费",
    description: "5/24 贵阳住宿，两间",
    date: "2026-05-24",
    amount: 266.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "携程旅行网 凯亚德酒店贵阳龙洞堡机场砂之船奥特莱斯店",
  },
  {
    id: 9,
    category: "住宿费",
    description: "5/25-5/26 济南住宿，两间",
    date: "2026-05-25",
    amount: 1054.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "华住酒店集团 桔子济南文化东路酒店,",
  },
  {
    id: 10,
    category: "住宿费",
    description: "5/27 泰山住宿，两间",
    date: "2026-05-24",
    amount: 660.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "携程旅行网 白玉兰酒店（泰山景区岱庙店）",
  },
  {
    id: 11,
    category: "住宿费",
    description: "5/27 济南住宿，两间",
    date: "2026-05-28",
    amount: 525.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "华住酒店集团 桔子济南文化东路酒店,",
  },
  {
    id: 12,
    category: "餐费",
    description: "5/20 晚饭，三人",
    date: "2026-05-20",
    amount: 73.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 去茶山（美的悦然时光店·咖啡·鲜奶茶·果茶）",
  },
  {
    id: 13,
    category: "餐费",
    description: "5/20 晚饭，三人",
    date: "2026-05-20",
    amount: 40.2,
    voucherType: "invoice",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 贞丰糯米饭（会展城店）",
  },
  {
    id: 14,
    category: "餐费",
    description: "5/21 咖啡，一人",
    date: "2026-05-21",
    amount: 15.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 Jillys Coffee茶几里（虎门巷店）",
  },
  {
    id: 15,
    category: "餐费",
    description: "5/21 咖啡，一人",
    date: "2026-05-21",
    amount: 15.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 Jillys Coffee茶几里（虎门巷店）",
  },
  {
    id: 16,
    category: "餐费",
    description: "5/21 咖啡，一人",
    date: "2026-05-21",
    amount: 23.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 Jillys Coffee茶几里（虎门巷店）",
  },
  {
    id: 17,
    category: "餐费",
    description: "5/21 早饭，四人",
    date: "2026-05-21",
    amount: 63.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "蒋家肠旺面",
  },
  {
    id: 18,
    category: "餐费",
    description: "5/21 午饭",
    date: "2026-05-21",
    amount: 93.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "周菊珍 /",
  },
  {
    id: 19,
    category: "餐费",
    description: "5/21 晚饭",
    date: "2026-05-21",
    amount: 290.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "孟关牛牛顺鲜牛馆 收款方备注:二维码收款付款方留言:0521晚饭",
  },
  {
    id: 20,
    category: "餐费",
    description: "5/21 夜宵 - 三人",
    date: "2026-05-21",
    amount: 26.68,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 喜三德甜品·糖水（冰浆·金融城店）",
  },
  {
    id: 21,
    category: "餐费",
    description: "5/21 夜宵 - 三人",
    date: "2026-05-21",
    amount: 44.52,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "K 凯辉 10648大关3店",
  },
  {
    id: 22,
    category: "餐费",
    description: "5/22 咖啡，三人",
    date: "2026-05-22",
    amount: 16.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 25Gahwa（咖瓦咖啡面包）",
  },
  {
    id: 23,
    category: "餐费",
    description: "5/22 咖啡，三人",
    date: "2026-05-22",
    amount: 20.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 25Gahwa（咖瓦咖啡面包）",
  },
  {
    id: 24,
    category: "餐费",
    description: "5/22 咖啡，三人",
    date: "2026-05-22",
    amount: 18.59,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 25Gahwa（咖瓦咖啡面包）",
  },
  {
    id: 25,
    category: "餐费",
    description: "5/22 早饭，斯人",
    date: "2026-05-22",
    amount: 52.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "文荣粉面馆 贵阳观山湖文荣餐饮店",
  },
  {
    id: 26,
    category: "餐费",
    description: "5/22 水、纸巾等",
    date: "2026-05-22",
    amount: 67.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "清宇便利店-送货到家 收款方备注:二维码收款付款方留言:05/22 午饭便利店零食水",
  },
  {
    id: 27,
    category: "餐费",
    description: "5/22 晚饭，四人",
    date: "2026-05-22",
    amount: 39.3,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 抹山序（甲秀楼店）",
  },
  {
    id: 28,
    category: "餐费",
    description: "5/22 晚饭，四人",
    date: "2026-05-22",
    amount: 305.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "贵阳云岩刘丽军火锅店",
  },
  {
    id: 29,
    category: "餐费",
    description: "5/23 路上面包",
    date: "2026-05-22",
    amount: 95.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "羊城西饼民生路店-消费",
  },
  {
    id: 30,
    category: "餐费",
    description: "5/23 路上零食",
    date: "2026-05-22",
    amount: 20.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "骆三姐土豆片店内购物",
  },
  {
    id: 31,
    category: "其他",
    description: "5/23 路上湿巾、水等",
    date: "2026-05-22",
    amount: 28.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "辣辣辣里辣 转账备注:濕巾水",
  },
  {
    id: 32,
    category: "餐费",
    description: "5/23 咖啡，三人",
    date: "2026-05-23",
    amount: 72.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 CaptainGeorge乔治队长(文昌店)",
  },
  {
    id: 33,
    category: "餐费",
    description: "5/23 午饭",
    date: "2026-05-23",
    amount: 27.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "荭龄便利店 0523 午饭",
  },
  {
    id: 34,
    category: "快递费",
    description: "5/23 快递费",
    date: "2026-05-23",
    amount: 41.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "德邦快递-DPK202747902521",
  },
  {
    id: 35,
    category: "餐费",
    description: "5/23 晚饭四人",
    date: "2026-05-23",
    amount: 238.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "廖桂英 收款方备注:二维码收款付款方留言:0523 晚饭",
  },
  {
    id: 36,
    category: "餐费",
    description: "5/23 电影票 情书",
    date: "2026-05-23",
    amount: 91.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团订单-26052311100300001306523700966830",
  },
  {
    id: 37,
    category: "餐费",
    description: "5/23 奶茶，三人",
    date: "2026-05-23",
    amount: 47.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "CHAGEE霸王茶姬（贵州黔南都匀市星乐城店）",
  },
  {
    id: 38,
    category: "交通费",
    description: "5/23 打车",
    date: "2026-05-24",
    amount: 8.01,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "滴滴出行 滴滴打车-尹师傅",
  },
  {
    id: 39,
    category: "餐费",
    description: "5/24 咖啡，三人",
    date: "2026-05-24",
    amount: 22.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 库迪咖啡(都匀万达广场店)",
  },
  {
    id: 40,
    category: "餐费",
    description: "5/24 咖啡，三人",
    date: "2026-05-24",
    amount: 15.5,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 库迪咖啡(都匀万达广场店)",
  },
  {
    id: 41,
    category: "餐费",
    description: "05/24 早饭",
    date: "2026-05-24",
    amount: 39.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "老苹果 收款方备注:二维码收款付款方留言:0524早飯",
  },
  {
    id: 42,
    category: "餐费",
    description: "05/24 晚饭，四人",
    date: "2026-05-24",
    amount: 74.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 去茶山（国贸新印1950店·咖啡·鲜奶茶·果茶）",
  },
  {
    id: 43,
    category: "餐费",
    description: "05/24 晚饭，四人",
    date: "2026-05-24",
    amount: 295.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-003.pdf",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    tpiaoIds: [],
    remark: "听涛拍岸 转账备注:0524 晚飯",
  },
  {
    id: 44,
    category: "餐费",
    description: "05/24 夜宵，三人",
    date: "2026-05-24",
    amount: 43.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 ZOONANA首尔炸鸡（太升国际店）",
  },
  {
    id: 45,
    category: "餐费",
    description: "05/24 夜宵，三人",
    date: "2026-05-24",
    amount: 43.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 首杨水果（首钢二店）",
  },
  {
    id: 46,
    category: "餐费",
    description: "05/25 咖啡，三人",
    date: "2026-05-25",
    amount: 95.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "去茶山 【堂食】_贵阳机场店T3航站楼（安检内）_267945",
  },
  {
    id: 47,
    category: "餐费",
    description: "05/26 爬山干粮，六人",
    date: "2026-05-25",
    amount: 319.83,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 711便利店（诚基中心店）",
  },
  {
    id: 48,
    category: "餐费",
    description: "05/26 爬山干粮，六人",
    date: "2026-05-25",
    amount: 65.82,
    voucherType: "invoice",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 名创优品24小时超级店（济南诚基中心店）",
  },
  {
    id: 49,
    category: "餐费",
    description: "05/26 爬山干粮，六人",
    date: "2026-05-25",
    amount: 74.94,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-022.pdf",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    tpiaoIds: [],
    remark: "美团 松鼠便利（山师店）",
  },
  {
    id: 50,
    category: "餐费",
    description: "05/26 爬山干粮，六人",
    date: "2026-05-25",
    amount: 59.93,
    voucherType: "invoice",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 松鼠便利（窑头店）",
  },
  {
    id: 51,
    category: "餐费",
    description: "05/26 咖啡，三人",
    date: "2026-05-26",
    amount: 35.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "luckin coffee 订单付款",
  },
  {
    id: 52,
    category: "餐费",
    description: "05/26 早饭，六人",
    date: "2026-05-26",
    amount: 57.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "晋同源兰悦中心店订单",
  },
  {
    id: 53,
    category: "交通费",
    description: "05/26 下山后打车到停车场",
    date: "2026-05-26",
    amount: 27.7,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "滴滴出行 滴滴快车打车-朱师傅-05月26日行程",
  },
  {
    id: 54,
    category: "餐费",
    description: "05/26 晚饭，三人",
    date: "2026-05-26",
    amount: 31.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 暖燕·姨妈热饮·现炖燕窝(山师店)",
  },
  {
    id: 55,
    category: "其他",
    description: "05/26 药",
    date: "2026-05-26",
    amount: 27.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 北京同仁堂（历山店）",
  },
  {
    id: 56,
    category: "餐费",
    description: "05/26 晚饭，三人",
    date: "2026-05-26",
    amount: 121.1,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 【元神御金汤】百合虫草花炖鲜鸡汤等10件商品",
  },
  {
    id: 57,
    category: "餐费",
    description: "05/26 晚饭，三人",
    date: "2026-05-26",
    amount: 144.01,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 【Street Shark（山师店）】美式经典芝士牛堡  …",
  },
  {
    id: 58,
    category: "其他",
    description: "辣辣辣里辣 转账备注:微信转账",
    date: "2026-05-26",
    amount: 213.52,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "",
  },
  {
    id: 59,
    category: "餐费",
    description: "05/27 堪景干粮，六人",
    date: "2026-05-26",
    amount: 41.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 松鼠便利（窑头店）",
  },
  {
    id: 60,
    category: "餐费",
    description: "05/27 堪景干粮，六人",
    date: "2026-05-26",
    amount: 38.2,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 松鼠便利（窑头店）",
  },
  {
    id: 61,
    category: "餐费",
    description: "05/27 堪景干粮，六人",
    date: "2026-05-26",
    amount: 76.58,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 711便利店（济南山师大北门店）",
  },
  {
    id: 62,
    category: "餐费",
    description: "05/27 咖啡，三人",
    date: "2026-05-27",
    amount: 52.59,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 WE LUCKY COFFEE现磨咖啡果茶（山大北路店）",
  },
  {
    id: 63,
    category: "餐费",
    description: "05/27 午饭，六人",
    date: "2026-05-27",
    amount: 134.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "山东丝路灵岩文化旅游有限公司运",
  },
  {
    id: 64,
    category: "其他",
    description: "05/27 爬山护具",
    date: "2026-05-27",
    amount: 269.02,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "京东-订单编号3511486014052261",
  },
  {
    id: 65,
    category: "交通费",
    description: "5/27 闪送费用",
    date: "2026-05-27",
    amount: 45.28,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "滴滴出行 订单费用",
  },
  {
    id: 66,
    category: "交通费",
    description: "5/27 泰山晚饭打车",
    date: "2026-05-27",
    amount: 8.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "滴滴出行 特惠快车打车-燕师傅-05月27日行程",
  },
  {
    id: 67,
    category: "餐费",
    description: "5/27 晚饭",
    date: "2026-05-27",
    amount: 70.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 喜茶(泰安金桥城店)",
  },
  {
    id: 68,
    category: "餐费",
    description: "5/28 泰山干粮，六人",
    date: "2026-05-27",
    amount: 58.52,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-021.pdf",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    tpiaoIds: [],
    remark: "美团 松鼠便利（泰安万达店）",
  },
  {
    id: 69,
    category: "餐费",
    description: "5/28 泰山干粮，六人",
    date: "2026-05-27",
    amount: 34.47,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "美团 好想来品牌零食（泰安泰山区东湖公园店）",
  },
  {
    id: 70,
    category: "交通费",
    description: "5/27 泰山晚饭打车",
    date: "2026-05-28",
    amount: 7.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-019.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    tpiaoIds: [],
    remark: "滴滴出行 特惠快车打车-许师傅-05月27日行程",
  },
  {
    id: 71,
    category: "餐费",
    description: "5/28 咖啡，三人",
    date: "2026-05-28",
    amount: 67.9,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/inv-024.pdf",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    tpiaoIds: [],
    remark: "美团 肯悦咖啡（泰安银座店）",
  },
  {
    id: 72,
    category: "餐费",
    description: "5/28 泰山上水",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
  },
  {
    id: 73,
    category: "餐费",
    description: "5/28 泰山上水",
    date: "2026-05-28",
    amount: 36.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
  },
  {
    id: 74,
    category: "餐费",
    description: "5/28 泰山上水",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "无人售货机 盛马售货机仅售2999元-外星人电解质水外星人电解质水外星人...",
  },
  {
    id: 75,
    category: "餐费",
    description: "5/28 泰山上水",
    date: "2026-05-28",
    amount: 48.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "无人售货机 盛马售货机仅售2999元-外星人电解水外星人电解水外星人电解...",
  },
  {
    id: 76,
    category: "餐费",
    description: "5/28 泰山午饭，六人",
    date: "2026-05-28",
    amount: 40.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "泰安市可栗香",
  },
  {
    id: 77,
    category: "餐费",
    description: "5/28 泰山午饭，六人",
    date: "2026-05-28",
    amount: 57.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "沪上阿姨 【堂食】_泰安泰山景区店_61318_37090204247",
  },
  {
    id: 78,
    category: "餐费",
    description: "5/28 泰山午饭，六人",
    date: "2026-05-28",
    amount: 196.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "昌盛快餐 /",
  },
  {
    id: 79,
    category: "业务招待费",
    description: "给堪景外联制片买烟",
    date: "2026-05-18",
    amount: 530.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-yan-530.jpg",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 80,
    category: "交通费",
    description: "堪景打车前往机场",
    date: "2026-05-20",
    amount: 109.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-jichang-109.jpg",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 81,
    category: "餐费",
    description: "导演、制片晚餐",
    date: "2026-05-28",
    amount: 131.6,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-dinner-131.jpg",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 82,
    category: "餐费",
    description: "导演、制片出发咖啡",
    date: "2026-05-29",
    amount: 35.72,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-coffee-35.jpg",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 83,
    category: "餐费",
    description: "导演、制片、协拍4人早餐",
    date: "2026-05-29",
    amount: 92.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-breakfast-92.jpg",
    invoiceFiles: [],
    invoiceCategory: "餐饮",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 84,
    category: "快递费",
    description: "器材快递回租赁公司(济南→北京)",
    date: "2026-05-29",
    amount: 106.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-sf-106.pdf",
    invoiceFiles: [],
    invoiceCategory: "快递服务",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 85,
    category: "快递费",
    description: "器材电池闪送回租赁公司",
    date: "2026-05-30",
    amount: 80.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-shansong-80.pdf",
    invoiceFiles: [],
    invoiceCategory: "快递服务",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 86,
    category: "差旅-交通",
    description: "导演济南回深圳机票",
    date: "2026-05-30",
    amount: 1097.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-jipiao-1097a.jpg",
    invoiceFiles: ["invoices/kanjing/lx-jipiao-1097b.jpg"],
    invoiceCategory: "客运服务费",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 87,
    category: "差旅-交通",
    description: "赵馨怡济南回北京高铁",
    date: "2026-05-30",
    amount: 223.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-gaotie-223.pdf",
    invoiceFiles: [],
    invoiceCategory: "客运服务费",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 88,
    category: "交通费",
    description: "制片济南打车到南站",
    date: "2026-05-30",
    amount: 24.6,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 89,
    category: "交通费",
    description: "制片出行打车行程(见行程单)",
    date: "2026-05-31",
    amount: 256.98,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/lx-didiA.pdf",
    invoiceFiles: ["invoices/kanjing/lx-didiB.pdf", "invoices/kanjing/lx-didiC.pdf", "invoices/kanjing/lx-didifpA.pdf", "invoices/kanjing/lx-didifpB.pdf", "invoices/kanjing/lx-didifpC.pdf"],
    invoiceCategory: "客运服务费",
    tpiaoIds: [],
    remark: "Lexie备用金实报（原5000借款，实支3956.34，退1043.66）",
  },
  {
    id: 90,
    category: "差旅-交通",
    description: "5/28 水素高铁 济南- 北京",
    date: "2026-05-28",
    amount: 223.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "中铁网络 12306消费",
  },
  {
    id: 91,
    category: "交通费",
    description: "5/28 水素 泰安- 济南",
    date: "2026-05-28",
    amount: 174.9,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "滴滴出行 特惠快车打车-刘师傅-05月28日行程",
  },
  {
    id: 92,
    category: "汽车费用",
    description: "勘景油费",
    date: "2026-05-22",
    amount: 520.0,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-youfei-520.pdf",
    invoiceFiles: [],
    invoiceCategory: "成品油",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 93,
    category: "汽车费用",
    description: "勘景油费",
    date: "2026-05-25",
    amount: 625.86,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-youfei-625.pdf",
    invoiceFiles: [],
    invoiceCategory: "成品油",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 94,
    category: "汽车费用",
    description: "勘景过路费",
    date: "2026-05-22",
    amount: 16.15,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-gonglu-1.pdf",
    invoiceFiles: [],
    invoiceCategory: "通行费",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 95,
    category: "汽车费用",
    description: "勘景过路费",
    date: "2026-05-23",
    amount: 57.76,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-gonglu-2.pdf",
    invoiceFiles: [],
    invoiceCategory: "通行费",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 96,
    category: "汽车费用",
    description: "勘景过路费",
    date: "2026-05-24",
    amount: 20.9,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-gonglu-3.pdf",
    invoiceFiles: [],
    invoiceCategory: "通行费",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 97,
    category: "汽车费用",
    description: "勘景过路费",
    date: "2026-05-24",
    amount: 33.4,
    voucherType: "invoice",
    invoiceFile: "invoices/kanjing/tq-gonglu-4.pdf",
    invoiceFiles: [],
    invoiceCategory: "通行费",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）",
  },
  {
    id: 98,
    category: "汽车费用",
    description: "勘景停车费",
    date: "2026-05-20",
    amount: 9.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 99,
    category: "汽车费用",
    description: "勘景停车费",
    date: "2026-05-20",
    amount: 6.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 100,
    category: "汽车费用",
    description: "勘景停车费",
    date: "2026-05-22",
    amount: 8.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 101,
    category: "汽车费用",
    description: "勘景停车费",
    date: "2026-05-23",
    amount: 2.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 102,
    category: "汽车费用",
    description: "勘景停车费",
    date: "2026-05-23",
    amount: 5.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 103,
    category: "餐费",
    description: "勘景早餐",
    date: "2026-05-23",
    amount: 40.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 104,
    category: "餐费",
    description: "勘景午餐",
    date: "2026-05-23",
    amount: 121.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 105,
    category: "器材",
    description: "无人机租赁(400元/天×5)",
    date: "2026-05-31",
    amount: 2000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 贵阳/都匀勘景实报（合计3465.07）（无票）",
  },
  {
    id: 106,
    category: "其他",
    description: "贵州外联费用",
    date: "2026-05-31",
    amount: 5000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "杨天奇 转账备注:堪景红包🧧",
  },
  {
    id: 107,
    category: "器材",
    description: "器材租赁",
    date: "2026-06-02",
    amount: 2000.0,
    voucherType: "none",
    invoiceFile: "",
    invoiceFiles: [],
    invoiceCategory: "",
    tpiaoIds: [],
    remark: "枪枪影视-器材租赁部 枪枪影视-器材租赁部 转账备注:5月20–29日10天器材租赁费用",
  }
];

const tpiaoList = [];
