// 工作日志 —— 每天的工作记录 + 待办。页面会按两周自动生成工作汇报。
// 记法见 worklog/README.md。只追加，不要删改历史记录。

const categories = [
  { key: "sound", name: "声音后期" },
  { key: "prod", name: "制片" },
  { key: "study", name: "留学" },
  { key: "other", name: "其他" }, // 搬家、还车等杂务，不进汇报
];

// 双周汇报交给廿一（投资方）。神舟是承担制作方。
// 只汇报和廿一有关的项目的制片 + 声音工作；无关的项目（如自己接的 WTRSO 副导演、Yamira、土星之环）不写。
const reportCats = ["prod", "sound"];
// 和廿一有关的项目（新项目和廿一有关时加进来）
const reportProjects = ["廿一", "色珍", "内藏班", "TIFF", "竹林遗录"];

// 每日记录：一件事一行。status: "done" 已完成 / "ongoing" 进行中
const logs = [
  // ---- 2026-09-28 ----
  { date: "2026-09-28", cat: "prod", project: "WTRSO", status: "ongoing",
    text: "制作 WTRSO schedule 及使用说明（使用说明未完成；schedule 还需确认部分演员细节）" },
  { date: "2026-09-28", cat: "study", project: "Allan creative video", status: "done",
    text: "完成 shotlist + script" },
  { date: "2026-09-28", cat: "study", project: "Allan creative video", status: "done",
    text: "Allan 拍摄" },
  { date: "2026-09-28", cat: "study", project: "Allan creative video", status: "done",
    text: "和 Allan 妈妈沟通拍摄情况" },
  { date: "2026-09-28", cat: "study", project: "Allan creative video", status: "done",
    text: "给 Yige 买拍摄回程的票" },
  { date: "2026-09-28", cat: "prod", project: "廿一", status: "done",
    text: "廿一 8 月、9 月工作总结" },
  { date: "2026-09-28", cat: "study", project: "Kate creative video", status: "done",
    text: "约 Kate creative video 会议时间" },
  { date: "2026-09-28", cat: "prod", project: "色珍", status: "done",
    text: "和色珍沟通约开会时间；更新后续工作待办事项" },
  { date: "2026-09-28", cat: "study", project: "Kimi", status: "done",
    text: "Kimi 图片解说写作" },
  { date: "2026-09-28", cat: "study", project: "留学 video 剪辑", status: "done",
    text: "和龚老师（留学 video 剪辑师）约会议时间，提前沟通会议内容" },
  { date: "2026-09-28", cat: "sound", project: "Cargo 个人网站", status: "done",
    text: "更新 Cargo 个人网站" },
  { date: "2026-09-28", cat: "prod", project: "内藏班", status: "done",
    text: "编写内藏班项目情况、策略及后续计划文件，发送给威姐" },
  { date: "2026-09-28", cat: "prod", project: "内藏班", status: "done",
    text: "内藏班预算更新" },
  { date: "2026-09-28", cat: "sound", project: "Yamira", status: "done",
    text: "查看 Yamira 的 note，并简单沟通" },

  // ---- 2026-09-30 ----
  { date: "2026-09-30", cat: "study", project: "Allan creative video", status: "done",
    text: "送 Allan 拍摄（island）的同事去车站" },
  { date: "2026-09-30", cat: "other", project: "搬家", status: "done",
    text: "从纽约开车到波士顿搬家；整理物品、清理丢弃、装箱" },
  { date: "2026-09-30", cat: "other", project: "搬家", status: "done",
    text: "还 Avis 租车，已结账" },
  { date: "2026-09-30", cat: "sound", project: "Yamira", status: "done",
    text: "就 Yamira 的 notes 进行沟通" },
  { date: "2026-09-30", cat: "sound", project: "Yamira", status: "done",
    text: "请合作声音设计师 Amelia 发送新的 Yamira pass" },
  { date: "2026-09-30", cat: "study", project: "留学 video 剪辑", status: "done",
    text: "与剪辑师沟通项目情况：后续几位学生的创意思路、拍摄进度及最终交付时间周期" },
  // 以下为 9/30 补充
  { date: "2026-09-30", cat: "prod", project: "TIFF", status: "done",
    text: "完成 TIFF 报销账单初稿" },
  { date: "2026-09-30", cat: "study", project: "Allan creative video", status: "done",
    text: "完成 Allan 拍摄报销账单初稿" },
  { date: "2026-09-30", cat: "prod", project: "WTRSO", status: "done",
    text: "WTRSO weekly meeting，更新 schedule" },
  { date: "2026-09-30", cat: "prod", project: "色珍", status: "done",
    text: "向色珍传达 Hot Docs 相关信息" },
  { date: "2026-09-30", cat: "study", project: "Jason", status: "done",
    text: "和 Jason 妈妈过素材及后续制作方案" },
  { date: "2026-09-30", cat: "study", project: "留学 video 剪辑", status: "done",
    text: "完成四位学生的 timeline 同步；和龚老师同步日历" },
  { date: "2026-09-30", cat: "study", project: "素材管理", status: "done",
    text: "解决 Google Drive 存储空间问题，上传并整理所有素材（含 Jason 素材 212 个文件归档）" },
  { date: "2026-09-30", cat: "sound", project: "土星之环", status: "done",
    text: "和导演沟通长片《土星之环》的声音创作方向" },
  { date: "2026-09-30", cat: "sound", project: "Yamira", status: "done",
    text: "修改 Yamira 并发出 2nd pass" },
  { date: "2026-09-30", cat: "sound", project: "竹林遗录", status: "done",
    text: "剪辑《竹林遗录》先导片声音并发出" },
  { date: "2026-09-30", cat: "study", project: "Jason", status: "done", src: "claude",
    text: "整理 Jason 录像 breakdown 与 shot list（45 个场景，标出 2 处缺口）" },
  { date: "2026-09-30", cat: "study", project: "助理交接", status: "ongoing", src: "claude",
    text: "起草助理岗位说明和工作交接档案（待定小助理的分工）" },
  { date: "2026-09-30", cat: "other", project: "Claude 工具", status: "done",
    text: "做了制片时间线（timetable）skill，以后可复用" },
  { date: "2026-09-30", cat: "other", project: "Claude 工具", status: "ongoing", src: "claude",
    text: "设置 Fathom 接入 Google Meet 做会议记录（未完成）" },
  { date: "2026-09-30", cat: "study", project: "supernova branding", status: "ongoing",
    text: "和 Claude 确认 supernova 的 branding 设计语言" },
  { date: "2026-09-30", cat: "other", project: "个人事务", status: "done",
    text: "还 Bilt 和 Apple Card 信用卡" },
  { date: "2026-09-30", cat: "other", project: "个人事务", status: "done",
    text: "找 Oura 申请戒指免费换新" },
  { date: "2026-09-30", cat: "other", project: "个人事务", status: "done",
    text: "健身：boxing" },
  { date: "2026-09-30", cat: "other", project: "个人事务", status: "done", src: "claude",
    text: "建立报税 write-off 记账表" },

  // ---- 2026-10-01（Claude 补充，待用户补当天清单）----
  { date: "2026-10-01", cat: "sound", project: "音效库", status: "done", src: "claude",
    text: "SNDLIB_HZ 音效库查重：扫描重复文件，出查重报告和清理脚本" },
  { date: "2026-10-01", cat: "sound", project: "混音邀约", status: "ongoing", src: "claude",
    text: "起草 Sound Mix Inquiry 回复邮件（询问粗剪、片长、混音档期、交付和预算）" },
  { date: "2026-10-01", cat: "sound", project: "机器人语音", status: "done", src: "claude",
    text: "研究机器人语音和「廉价影院喇叭」效果的处理链，比较环绕声插件" },
  { date: "2026-10-01", cat: "study", project: "Jason", status: "done", src: "claude",
    text: "完善 Jason recording breakdown：6 段录像的精确时间码、重叠和缺失片段" },
  { date: "2026-10-01", cat: "study", project: "报销", status: "done", src: "claude",
    text: "按 Uber 记录修正 Amex 报销表里 21 处日期和类目" },
  { date: "2026-10-01", cat: "study", project: "助理交接", status: "ongoing", src: "claude",
    text: "更新助理岗位说明和交接档案" },
  { date: "2026-10-01", cat: "other", project: "Claude 工具", status: "done", src: "claude",
    text: "统一制片时间线模板（Cloudflare 和 Claude 两版同步）；更新待办看板（日期选择、今日聚焦）" },
  { date: "2026-10-01", cat: "other", project: "个人事务", status: "done", src: "claude",
    text: "租房方案分析" },

  // ---- 2026-10-02 ----
  { date: "2026-10-02", cat: "sound", project: "土星之环", status: "ongoing",
    text: "《土星之环》声音做到 cinema 2" },
  { date: "2026-10-02", cat: "study", project: "Kate creative video", status: "done",
    text: "Kate creative video brainstorm" },
  { date: "2026-10-02", cat: "study", project: "Kate creative video", status: "done",
    text: "整理 brainstorm 会议记录" },
  { date: "2026-10-02", cat: "study", project: "助理交接", status: "done",
    text: "和留学小助理开会，讨论小红书帖子怎么发" },
  { date: "2026-10-02", cat: "study", project: "video essay 方法论", status: "done",
    text: "总结 video essay 方法论" },
  { date: "2026-10-02", cat: "sound", project: "Yamira", status: "done",
    text: "回复 Yamira note，确认 2nd pass 的 note 情况" },
  { date: "2026-10-02", cat: "study", project: "助理交接", status: "done",
    text: "和小助理简单沟通分工和助理任务" },
  { date: "2026-10-02", cat: "other", project: "个人事务", status: "done",
    text: "确定下周去纽约的计划，谈好住处" },
  { date: "2026-10-02", cat: "other", project: "个人事务", status: "done",
    text: "买回国机票" },
  { date: "2026-10-02", cat: "sound", project: "机器人语音", status: "done", src: "claude",
    text: "整理「廉价影院喇叭」效果处理链（滤波、EQ、失真、大厅混响、空间定位，加 worldizing 建议）" },
  { date: "2026-10-02", cat: "sound", project: "Mottainai", status: "done", src: "claude",
    text: "评估 Mottainai 项目合作：查 Kickstarter 进度和合作方背景，建议在 deal memo 里锁定修改版本数" },
  { date: "2026-10-02", cat: "study", project: "Chelsea", status: "ongoing", src: "claude",
    text: "整理 Chelsea 秋季课的排课信息" },
  { date: "2026-10-02", cat: "other", project: "个人事务", status: "done", src: "claude",
    text: "查 10/5 或 10/6 波士顿→纽约的 Amtrak 车次" },
  { date: "2026-10-02", cat: "other", project: "个人事务", status: "ongoing", src: "claude",
    text: "研究信用卡积分转航空里程方案" },
];

// 待办：owner "我" 会进汇报的「下两周计划」；"秘书" 是交给秘书的事。
// status: "open" 待做 / "waiting" 等条件 / "done" 完成（完成时填 doneDate）
const todos = [
  { id: 1, cat: "prod", project: "WTRSO", owner: "我", status: "open", created: "2026-09-28", due: "2026-10-12",
    text: "完成 WTRSO 使用说明" },
  { id: 2, cat: "prod", project: "WTRSO", owner: "我", status: "open", created: "2026-09-28", due: "2026-10-12",
    text: "schedule：确认演员细节" },
  { id: 3, cat: "prod", project: "WTRSO", owner: "我", status: "open", created: "2026-09-28", due: "2026-10-12",
    text: "schedule：标记 tag" },
  { id: 4, cat: "prod", project: "WTRSO", owner: "我", status: "open", created: "2026-09-28", due: "2026-10-12",
    text: "schedule：转到 MMS", note: "看看能否交给 Yifei 转到 Movie Magic" },
  { id: 5, cat: "study", project: "Allan creative video", owner: "秘书", status: "open", created: "2026-09-28", due: "",
    text: "给 Allan 妈妈整理账单、报销费用", note: "Avis 已于 9/30 结账；AI 已出初稿，待核对" },
  { id: 6, cat: "sound", project: "Yamira", owner: "我", status: "done", created: "2026-09-28", due: "2026-09-29", doneDate: "2026-09-30",
    text: "根据 Yamira 的 note 做准备", note: "9/29 早上 8:00–9:00；9/30 已发 2nd pass" },
  { id: 7, cat: "sound", project: "Yamira", owner: "我", status: "done", created: "2026-09-30", due: "", doneDate: "2026-09-30",
    text: "收到新的 Yamira pass 后继续", note: "等 Amelia（合作声音设计师）发来" },
  { id: 8, cat: "study", project: "报销", owner: "我", status: "done", created: "2026-09-30", plan: "2026-10-01", due: "", doneDate: "2026-09-30",
    text: "让 AI 读 Amex 账单，整理这几天的报销" },
  { id: 9, cat: "study", project: "报销", owner: "我", status: "open", created: "2026-09-30", plan: "2026-10-01", due: "",
    text: "找 Yige 要她那边的报销" },
  { id: 10, cat: "prod", project: "WTRSO", owner: "我", status: "open", created: "2026-09-30", due: "",
    text: "把 schedule 相关工作分派给 Yifei" },
  { id: 11, cat: "study", project: "素材管理", owner: "我", status: "open", created: "2026-09-30", due: "",
    text: "回复 Isabella，让她上传素材" },
  { id: 12, cat: "study", project: "留学 video 剪辑", owner: "我", status: "open", created: "2026-09-30", due: "",
    text: "和龚老师同步所有内容：用腾讯会议转录整理会议记录，发给龚老师" },
  { id: 13, cat: "study", project: "Jason", owner: "我", status: "open", created: "2026-09-30", plan: "2026-10-01", due: "",
    text: "过 Jason 素材" },
  { id: 14, cat: "study", project: "报销", owner: "我", status: "open", created: "2026-09-30", plan: "2026-10-01", due: "",
    text: "确认 Amex 账单里 3 个待定项：9/17 的 $1 Uber、Airbnb 日期、非 Uber 餐费收据" },
  { id: 15, cat: "sound", project: "混音邀约", owner: "我", status: "open", created: "2026-10-01", due: "",
    text: "审阅并发出混音邀约回复邮件", note: "要补：deck 状态、Grace 的邮箱、10 月档期、预算问题" },
  { id: 16, cat: "sound", project: "音效库", owner: "我", status: "open", created: "2026-10-01", due: "",
    text: "决定是否清理音效库重复文件", note: "建议先移到 _DUPES_待删 文件夹，之后 Soundminer 重扫" },
  { id: 17, cat: "study", project: "助理交接", owner: "我", status: "done", created: "2026-10-01", due: "", doneDate: "2026-10-02",
    text: "决定小助理的分工：留学排期 + 笔记，还是只做社媒" },
  { id: 18, cat: "study", project: "Chelsea", owner: "我", status: "open", created: "2026-10-02", due: "",
    text: "约 Chelsea 秋季课：回复排课问题，审阅发给家长的约课消息" },
  { id: 19, cat: "other", project: "个人事务", owner: "我", status: "open", created: "2026-10-02", due: "",
    text: "确认 EdiLoad、Spill、Speakerphone 插件分别是为哪个项目买的（报税用）" },
  { id: 20, cat: "other", project: "个人事务", owner: "我", status: "open", created: "2026-10-02", due: "",
    text: "定目的地，判断积分转 Flying Blue 是否划算" },
  { id: 21, cat: "other", project: "个人事务", owner: "我", status: "open", created: "2026-10-02", plan: "2026-10-03", due: "",
    text: "买波士顿⇄纽约往返车票" },
  { id: 22, cat: "other", project: "个人事务", owner: "我", status: "open", created: "2026-10-02", plan: "2026-10-03", due: "",
    text: "和租房姐姐沟通" },
];
