// 工作日志 —— 每天的工作记录 + 待办。页面会按两周自动生成工作汇报。
// 记法见 worklog/README.md。只追加，不要删改历史记录。

const categories = [
  { key: "sound", name: "声音后期" },
  { key: "prod", name: "制片" },
  { key: "study", name: "留学" },
  { key: "other", name: "其他" }, // 搬家、还车等杂务，不进汇报
];

// 双周汇报交给廿一（投资方）。神舟是承担制作方。
// 只汇报和廿一有关的项目的制片 + 声音工作；无关的项目（如自己接的 WTRSO 副导演、Yamira、土星之环）不写。
const reportCats = ["prod", "sound"];
// 和廿一有关的项目（新项目和廿一有关时加进来）
const reportProjects = ["廿一", "色珍", "色珍新长片", "内藏班", "TIFF", "黑豆", "竹林遗录"];

// 每日记录：一件事一行。status: "done" 已完成 / "ongoing" 进行中
const logs = [
  // ---- 2026-09-28 ----
  { date: "2026-09-28", cat: "prod", project: "WTRSO", status: "ongoing",
    text: "制作 WTRSO schedule 及使用说明（使用说明未完成；schedule 还需确认部分演员细节）" },
  { date: "2026-09-28", cat: "study", project: "Allan creative video", status: "done",
    text: "完成 shotlist + script" },
  { date: "2026-09-28", cat: "study", project: "Allan creative video", status: "done",
    text: "Allan 拍摄" },
  { date: "2026-09-28", cat: "study", project: "Allan creative video", status: "done",
    text: "和 Allan 妈妈沟通拍摄情况" },
  { date: "2026-09-28", cat: "study", project: "Allan creative video", status: "done",
    text: "给 Yige 买拍摄回程的票" },
  { date: "2026-09-28", cat: "prod", project: "廿一", status: "done",
    text: "廿一 8 月、9 月工作总结" },
  { date: "2026-09-28", cat: "study", project: "Kate creative video", status: "done",
    text: "约 Kate creative video 会议时间" },
  { date: "2026-09-28", cat: "prod", project: "色珍", status: "done",
    text: "和色珍沟通约开会时间；更新后续工作待办事项" },
  { date: "2026-09-28", cat: "study", project: "Kimi", status: "done",
    text: "Kimi 图片解说写作" },
  { date: "2026-09-28", cat: "study", project: "留学 video 剪辑", status: "done",
    text: "和龚老师（留学 video 剪辑师）约会议时间，提前沟通会议内容" },
  { date: "2026-09-28", cat: "sound", project: "Cargo 个人网站", status: "done",
    text: "更新 Cargo 个人网站" },
  { date: "2026-09-28", cat: "prod", project: "内藏班", status: "done",
    text: "编写内藏班项目情况、策略及后续计划文件，发送给威姐" },
  { date: "2026-09-28", cat: "prod", project: "内藏班", status: "done",
    text: "内藏班预算更新" },
  { date: "2026-09-28", cat: "sound", project: "Yamira", status: "done",
    text: "查看 Yamira 的 note，并简单沟通" },

  // ---- 2026-09-30 ----
  { date: "2026-09-30", cat: "study", project: "Allan creative video", status: "done",
    text: "送 Allan 拍摄（island）的同事去车站" },
  { date: "2026-09-30", cat: "other", project: "搬家", status: "done",
    text: "从纽约开车到波士顿搬家；整理物品、清理丢弃、装箱" },
  { date: "2026-09-30", cat: "other", project: "搬家", status: "done",
    text: "还 Avis 租车，已结账" },
  { date: "2026-09-30", cat: "sound", project: "Yamira", status: "done",
    text: "就 Yamira 的 notes 进行沟通" },
  { date: "2026-09-30", cat: "sound", project: "Yamira", status: "done",
    text: "请合作声音设计师 Amelia 发送新的 Yamira pass" },
  { date: "2026-09-30", cat: "study", project: "留学 video 剪辑", status: "done",
    text: "与剪辑师沟通项目情况：后续几位学生的创意思路、拍摄进度及最终交付时间周期" },
  // 以下为 9/30 补充
  { date: "2026-09-30", cat: "prod", project: "TIFF", status: "done",
    text: "完成 TIFF 报销账单初稿" },
  { date: "2026-09-30", cat: "study", project: "Allan creative video", status: "done",
    text: "完成 Allan 拍摄报销账单初稿" },
  { date: "2026-09-30", cat: "prod", project: "WTRSO", status: "done",
    text: "WTRSO weekly meeting，更新 schedule" },
  { date: "2026-09-30", cat: "prod", project: "色珍", status: "done",
    text: "向色珍传达 Hot Docs 相关信息" },
  { date: "2026-09-30", cat: "study", project: "Jason", status: "done",
    text: "和 Jason 妈妈过素材及后续制作方案" },
  { date: "2026-09-30", cat: "study", project: "留学 video 剪辑", status: "done",
    text: "完成四位学生的 timeline 同步；和龚老师同步日历" },
  { date: "2026-09-30", cat: "study", project: "素材管理", status: "done",
    text: "解决 Google Drive 存储空间问题，上传并整理所有素材（含 Jason 素材 212 个文件归档）" },
  { date: "2026-09-30", cat: "sound", project: "土星之环", status: "done",
    text: "和导演沟通长片《土星之环》的声音创作方向" },
  { date: "2026-09-30", cat: "sound", project: "Yamira", status: "done",
    text: "修改 Yamira 并发出 2nd pass" },
  { date: "2026-09-30", cat: "sound", project: "竹林遗录", status: "done",
    text: "剪辑《竹林遗录》先导片声音并发出" },
  { date: "2026-09-30", cat: "study", project: "Jason", status: "done", src: "claude",
    text: "整理 Jason 录像 breakdown 与 shot list（45 个场景，标出 2 处缺口）" },
  { date: "2026-09-30", cat: "study", project: "助理交接", status: "ongoing", src: "claude",
    text: "起草助理岗位说明和工作交接档案（待定小助理的分工）" },
  { date: "2026-09-30", cat: "other", project: "Claude 工具", status: "done",
    text: "做了制片时间线（timetable）skill，以后可复用" },
  { date: "2026-09-30", cat: "other", project: "Claude 工具", status: "ongoing", src: "claude",
    text: "设置 Fathom 接入 Google Meet 做会议记录（未完成）" },
  { date: "2026-09-30", cat: "study", project: "supernova branding", status: "ongoing",
    text: "和 Claude 确认 supernova 的 branding 设计语言" },
  { date: "2026-09-30", cat: "other", project: "个人事务", status: "done",
    text: "还 Bilt 和 Apple Card 信用卡" },
  { date: "2026-09-30", cat: "other", project: "个人事务", status: "done",
    text: "找 Oura 申请戒指免费换新" },
  { date: "2026-09-30", cat: "other", project: "个人事务", status: "done",
    text: "健身：boxing" },
  { date: "2026-09-30", cat: "other", project: "个人事务", status: "done", src: "claude",
    text: "建立报税 write-off 记账表" },

  // ---- 2026-10-01（Claude 补充，待用户补当天清单）----
  { date: "2026-10-01", cat: "sound", project: "音效库", status: "done", src: "claude",
    text: "SNDLIB_HZ 音效库查重：扫描重复文件，出查重报告和清理脚本" },
  { date: "2026-10-01", cat: "sound", project: "混音邀约", status: "ongoing", src: "claude",
    text: "起草 Sound Mix Inquiry 回复邮件（询问粗剪、片长、混音档期、交付和预算）" },
  { date: "2026-10-01", cat: "sound", project: "机器人语音", status: "done", src: "claude",
    text: "研究机器人语音和「廉价影院喇叭」效果的处理链，比较环绕声插件" },
  { date: "2026-10-01", cat: "study", project: "Jason", status: "done", src: "claude",
    text: "完善 Jason recording breakdown：6 段录像的精确时间码、重叠和缺失片段" },
  { date: "2026-10-01", cat: "study", project: "报销", status: "done", src: "claude",
    text: "按 Uber 记录修正 Amex 报销表里 21 处日期和类目" },
  { date: "2026-10-01", cat: "study", project: "助理交接", status: "ongoing", src: "claude",
    text: "更新助理岗位说明和交接档案" },
  { date: "2026-10-01", cat: "other", project: "Claude 工具", status: "done", src: "claude",
    text: "统一制片时间线模板（Cloudflare 和 Claude 两版同步）；更新待办看板（日期选择、今日聚焦）" },
  { date: "2026-10-01", cat: "other", project: "个人事务", status: "done", src: "claude",
    text: "租房方案分析" },

  // ---- 2026-10-02 ----
  { date: "2026-10-02", cat: "sound", project: "土星之环", status: "ongoing",
    text: "《土星之环》声音做到 cinema 2" },
  { date: "2026-10-02", cat: "study", project: "Kate creative video", status: "done",
    text: "Kate creative video brainstorm" },
  { date: "2026-10-02", cat: "study", project: "Kate creative video", status: "done",
    text: "整理 brainstorm 会议记录" },
  { date: "2026-10-02", cat: "study", project: "助理交接", status: "done",
    text: "和留学小助理开会，讨论小红书帖子怎么发" },
  { date: "2026-10-02", cat: "study", project: "video essay 方法论", status: "done",
    text: "总结 video essay 方法论" },
  { date: "2026-10-02", cat: "sound", project: "Yamira", status: "done",
    text: "回复 Yamira note，确认 2nd pass 的 note 情况" },
  { date: "2026-10-02", cat: "study", project: "助理交接", status: "done",
    text: "和小助理简单沟通分工和助理任务" },
  { date: "2026-10-02", cat: "other", project: "个人事务", status: "done",
    text: "确定下周去纽约的计划，谈好住处" },
  { date: "2026-10-02", cat: "other", project: "个人事务", status: "done",
    text: "买回国机票" },
  { date: "2026-10-02", cat: "sound", project: "机器人语音", status: "done", src: "claude",
    text: "整理「廉价影院喇叭」效果处理链（滤波、EQ、失真、大厅混响、空间定位，加 worldizing 建议）" },
  { date: "2026-10-02", cat: "sound", project: "Mottainai", status: "done", src: "claude",
    text: "评估 Mottainai 项目合作：查 Kickstarter 进度和合作方背景，建议在 deal memo 里锁定修改版本数" },
  { date: "2026-10-02", cat: "study", project: "Chelsea", status: "ongoing", src: "claude",
    text: "整理 Chelsea 秋季课的排课信息" },
  { date: "2026-10-02", cat: "other", project: "个人事务", status: "done", src: "claude",
    text: "查 10/5 或 10/6 波士顿→纽约的 Amtrak 车次" },
  { date: "2026-10-02", cat: "other", project: "个人事务", status: "ongoing", src: "claude",
    text: "研究信用卡积分转航空里程方案" },

  // ---- 2026-10-03 ----
  { date: "2026-10-03", cat: "sound", project: "Yamira", status: "done",
    text: "发出 Yamira 3rd pass" },
  { date: "2026-10-03", cat: "sound", project: "土星之环", status: "done",
    text: "和导演沟通《土星之环》前十分钟的内容情况" },
  { date: "2026-10-03", cat: "sound", project: "土星之环", status: "done",
    text: "和 Juliette 过《土星之环》素材" },
  { date: "2026-10-03", cat: "sound", project: "混音棚", status: "done",
    text: "退订 mix stage" },
  { date: "2026-10-03", cat: "prod", project: "WTRSO", status: "done",
    text: "约 Yifei 开会" },
  { date: "2026-10-03", cat: "study", project: "留学 video 剪辑", status: "done",
    text: "和龚老师约 Jason 的会议" },
  { date: "2026-10-03", cat: "study", project: "Allan creative video", status: "done",
    text: "跟进 Allan 素材" },
  { date: "2026-10-03", cat: "study", project: "素材管理", status: "done",
    text: "确认 Isabella 的素材" },
  { date: "2026-10-03", cat: "study", project: "助理交接", status: "done",
    text: "和小助理确认可以帮忙提醒的工作内容" },
  { date: "2026-10-03", cat: "other", project: "个人事务", status: "done",
    text: "和租房姐姐沟通" },
  { date: "2026-10-03", cat: "other", project: "个人事务", status: "done",
    text: "订回 BOS 的机票" },
  { date: "2026-10-03", cat: "other", project: "个人事务", status: "done",
    text: "Walmart 采购纽约住宿用品；Amazon 买显示器" },
  { date: "2026-10-03", cat: "other", project: "个人事务", status: "done",
    text: "和 wxz 约见面时间" },
  { date: "2026-10-03", cat: "other", project: "个人事务", status: "done",
    text: "午饭外出；买鼻炎药" },
  { date: "2026-10-03", cat: "sound", project: "海景房", status: "ongoing",
    text: "沟通《海景房》混音时间" },

  // ---- 2026-10-04 ----
  { date: "2026-10-04", cat: "prod", project: "WTRSO", status: "done", src: "claude",
    text: "和 Yifei 沟通需求" },
  { date: "2026-10-04", cat: "prod", project: "内藏班", status: "done", src: "claude",
    text: "回复黄骥的消息（ECHO 剪辑）" },
  { date: "2026-10-04", cat: "sound", project: "音效库", status: "done", src: "claude",
    text: "SNDLIB_HZ 音效库去重：约 7.6 万个重复文件移入待删文件夹并抽查校验" },
  { date: "2026-10-04", cat: "study", project: "助理交接", status: "done", src: "claude",
    text: "更新助理岗位说明和交接手册，整理「待水素决定」清单" },
  { date: "2026-10-04", cat: "other", project: "Claude 工具", status: "done", src: "claude",
    text: "搭「水素 OS」总览；调研可装的工具（apple-mail-mcp、urlwatch、OpenTimelineIO 等）" },
  { date: "2026-10-04", cat: "sound", project: "土星之环", status: "ongoing",
    text: "《土星之环》声音推进一部分" },
  { date: "2026-10-04", cat: "sound", project: "AAF", status: "done",
    text: "重新导出丢失文件的 AAF" },
  { date: "2026-10-04", cat: "study", project: "Kate creative video", status: "done",
    text: "收到 Kate 剧本反馈" },
  { date: "2026-10-04", cat: "other", project: "璞识 brand guideline", status: "ongoing",
    text: "联系璞识做 brand guideline 设计，设计师已回复" },
  { date: "2026-10-04", cat: "other", project: "个人事务", status: "done",
    text: "跟踪 Oura 换新包裹" },
];

// 待办以「水素的待办板」为准（私密）。这里只是工作类待办的公开镜像，每天早上自动从待办板同步，不要手改。
// 个人/行政类（行程生活、公司行政、网站品牌、其他）不镜像到这里。
const todos = [
  { id: "t540aef5e", cat: "sound", project: "声音客户", owner: "我", status: "open", due: "", text: "renner 新 video short" },
  { id: "t86d71a24", cat: "sound", project: "声音客户", owner: "我", status: "open", due: "2026-10-04", text: "回 Yixin：Sound Mix Inquiry 给 rate" },
  { id: "tfd407b9b", cat: "prod", project: "竹林遗录", owner: "我", status: "waiting", due: "2026-11-05", text: "11/5 16:00 CET TFL FeatureLab 2027 截止（竹林遗录）" },
  { id: "t545070f6", cat: "sound", project: "声音客户", owner: "我", status: "waiting", due: "", text: "弄 Rishabh 的东西" },
  { id: "ta114359f", cat: "study", project: "留学", owner: "我", status: "waiting", due: "", text: "先和剪辑师过一遍 Jason 的素材，定怎么剪" },
  { id: "tde8538e0", cat: "prod", project: "色珍新长片", owner: "我", status: "waiting", due: "", text: "TFL ScriptLab 2027 call 公布（色珍新 narrative 长片）" },
  { id: "t8c1321ed", cat: "prod", project: "黑豆", owner: "我", status: "open", due: "", text: "回复 OMNI TV 采访请求" },
  { id: "t2496cb7f", cat: "prod", project: "黑豆", owner: "我", status: "open", due: "", text: "下载 TIFF26 首映官方照片" },
  { id: "t7d48d06f", cat: "prod", project: "黑豆", owner: "我", status: "waiting", due: "", text: "IFFR 2027《黑豆》参展" },
  { id: "t0dd993ac", cat: "sound", project: "声音客户", owner: "我", status: "waiting", due: "", text: "FabFilter Pro-DS 等黑五折扣再买" },
  { id: "t924e2d28", cat: "prod", project: "内藏班", owner: "我", status: "open", due: "2026-12-10", text: "12/10 Hot Docs 2027 成片提交 regular（内藏班，跳过 10/29 early）" },
  { id: "bmup4vtut6ytc", cat: "prod", project: "WTRSO", owner: "我", status: "waiting", due: "", text: "发最新的stripboad" },
  { id: "ta3e29ac9", cat: "prod", project: "内藏班", owner: "我", status: "open", due: "2026-11-03", text: "11/3 CPH:ROUGHCUT 2027 截止（内藏班）" },
  { id: "t25942d69", cat: "prod", project: "内藏班", owner: "我", status: "open", due: "", text: "DFI Spring 2027：只申内藏班后期（纪录片最高 US$50,000）" },
  { id: "tf6eaa192", cat: "study", project: "留学", owner: "我", status: "waiting", due: "", text: "留学公司介绍、服务介绍" },
  { id: "t9ab1e4b7", cat: "prod", project: "内藏班", owner: "我", status: "open", due: "", text: "2027-02-10 IDFA Bertha Fund Classic（内藏班）" },
  { id: "t37793c69", cat: "prod", project: "内藏班", owner: "我", status: "open", due: "", text: "ECHO / 内藏班：为 TFL Audience Design Fund 2027 找欧洲合拍方或销售代理" },
  { id: "bmup4wso57zxh", cat: "prod", project: "内藏班", owner: "我", status: "open", due: "2026-10-04", text: "约和色珍的会议 聊 今年后面的计划" },
  { id: "bmup508k7nmtw", cat: "study", project: "留学", owner: "我", status: "open", due: "2026-10-05", text: "缕jason思路 做script 分镜表格" },
  { id: "bmup50zovpq9k", cat: "sound", project: "声音客户", owner: "我", status: "open", due: "", text: "找人做plain background" },
  { id: "bmup50v52y3m0", cat: "sound", project: "声音客户", owner: "我", status: "open", due: "", text: "找人帮我做scene marker" },
  { id: "t68be6a97", cat: "prod", project: "竹林遗录", owner: "我", status: "open", due: "2026-10-30", text: "10/30 23:59 HKT HAF IDP 2027 常规截止（竹林遗录）" },
  { id: "bmutgjyvc18sj", cat: "study", project: "留学", owner: "我", status: "open", due: "2026-10-04", text: "allan账单发送" },
  { id: "bmutgk4kmufb1", cat: "study", project: "留学", owner: "我", status: "open", due: "", text: "allan 时间线要发给家长" },
  { id: "bmutwenfixxnc", cat: "prod", project: "内藏班", owner: "我", status: "open", due: "2026-10-05", text: "约了和yige的会议 周一晚上10pm est" },
  { id: "bmutf51eh1tir", cat: "study", project: "留学", owner: "我", status: "open", due: "", text: "给allan妈妈报账单" },
  { id: "w1", cat: "prod", project: "WTRSO", owner: "我", status: "open", due: "2026-10-12", text: "完成 WTRSO 使用说明" },
  { id: "w2", cat: "prod", project: "WTRSO", owner: "我", status: "open", due: "2026-10-12", text: "WTRSO schedule：确认演员细节" },
  { id: "w3", cat: "prod", project: "WTRSO", owner: "我", status: "open", due: "2026-10-12", text: "WTRSO schedule：标记 tag" },
  { id: "w4", cat: "prod", project: "WTRSO", owner: "我", status: "open", due: "2026-10-12", text: "WTRSO schedule 转到 Movie Magic" },
  { id: "w10", cat: "prod", project: "WTRSO", owner: "我", status: "open", due: "", text: "把 schedule 相关工作分派给 Yifei" },
  { id: "w9", cat: "study", project: "留学", owner: "我", status: "open", due: "", text: "找 Yige 要她那边的报销" },
  { id: "w12", cat: "study", project: "留学", owner: "我", status: "open", due: "", text: "和龚老师同步所有内容：腾讯会议转录整理会议记录，发给龚老师" },
  { id: "w14", cat: "study", project: "留学", owner: "我", status: "open", due: "", text: "确认 Amex 报销表 3 个待定项" },
  { id: "w18", cat: "study", project: "留学", owner: "我", status: "open", due: "", text: "约 Chelsea 秋季课：回复排课问题，审阅发给家长的约课消息" },
  { id: "w16", cat: "sound", project: "土星", owner: "我", status: "open", due: "", text: "音效库查重：决定 4 个特殊情况" },
  { id: "w23", cat: "sound", project: "声音客户", owner: "我", status: "waiting", due: "", text: "确定《海景房》混音时间" },
  { id: "w25", cat: "study", project: "留学", owner: "我", status: "open", due: "2026-10-05", text: "Kate：按剧本反馈更新脚本和 shotlist（剪辑师用版本）" },
  { id: "w26", cat: "study", project: "留学", owner: "我", status: "waiting", due: "2026-10-05", text: "Isabella 发带音符的素材" },
];
